BluFedora Job System: Job::SPSCQueue< T > Class Template Reference
Job::SPSCQueue< T > Class Template Reference
#include <job_queue.hpp>
Public Types
using size_type = std::size_t
using atomic_size_type = std::atomic< size_type >
Public Member Functions
SPSCQueue ()=default
~SPSCQueue ()=default
void Initialize (T *const memory_backing, const size_type capacity) noexcept
bool Push (const T &value)
bool Pop (T *const out_value)
template<typename CallbackFn >
bool PushLazy (CallbackFn &&callback)
template<typename CallbackFn >
bool PopLazy (CallbackFn &&callback)
Private Member Functions
bool IsFull (const size_type head, const size_type tail) const noexcept
T * ElementAt (const size_type index) const noexcept
Static Private Member Functions
static bool IsEmpty (const size_type head, const size_type tail) noexcept
Private Attributes
atomic_size_type m_ProducerIndex
unsigned char m_Padding0 [k_FalseSharingPadSize - sizeof(m_ProducerIndex)]
size_type m_CachedConsumerIndex
unsigned char m_Padding1 [k_FalseSharingPadSize - sizeof(m_CachedConsumerIndex)]
atomic_size_type m_ConsumerIndex
unsigned char m_Padding2 [k_FalseSharingPadSize - sizeof(m_ConsumerIndex)]
size_type m_CachedProducerIndex
unsigned char m_Padding3 [k_FalseSharingPadSize - sizeof(m_CachedProducerIndex)]
T * m_Data
size_type m_Capacity
size_type m_CapacityMask
unsigned char m_Padding4 [k_FalseSharingPadSize - sizeof(m_Data) - sizeof(m_Capacity) - sizeof(m_CapacityMask)]
Detailed Description
template<typename T>
class Job::SPSCQueue< T >
Definition at line 111 of file job_queue.hpp.
Member Typedef Documentation
size_type
template<typename T > using Job::SPSCQueue< T >::size_type = std::size_t
Definition at line 114 of file job_queue.hpp.
atomic_size_type
template<typename T > using Job::SPSCQueue< T >::atomic_size_type = std::atomic<size_type>
Definition at line 115 of file job_queue.hpp.
Constructor & Destructor Documentation
SPSCQueue()
template<typename T > Job::SPSCQueue< T >::SPSCQueue () default
~SPSCQueue()
template<typename T > Job::SPSCQueue< T >::~SPSCQueue () default
Member Function Documentation
Initialize()
template<typename T > void Job::SPSCQueue< T >::Initialize (T *const memory_backing, const size_type capacity) inline noexcept
Definition at line 145 of file job_queue.hpp.
    {
      m_ProducerIndex.store(0, std::memory_order_relaxed);
      m_CachedConsumerIndex = 0;
      m_ConsumerIndex.store(0, std::memory_order_relaxed);
      m_CachedProducerIndex = 0;
      m_Data                = memory_backing;
      m_Capacity            = capacity;
      m_CapacityMask        = capacity - 1;
      JobAssert((m_Capacity & m_CapacityMask) == 0, "Capacity must be a power of 2.");
    }
References JobAssert, Job::SPSCQueue< T >::m_CachedConsumerIndex, Job::SPSCQueue< T >::m_CachedProducerIndex, Job::SPSCQueue< T >::m_Capacity, Job::SPSCQueue< T >::m_CapacityMask, Job::SPSCQueue< T >::m_ConsumerIndex, Job::SPSCQueue< T >::m_Data, and Job::SPSCQueue< T >::m_ProducerIndex.
Push()
template<typename T > bool Job::SPSCQueue< T >::Push (const T & value) inline
Definition at line 158 of file job_queue.hpp.
    {
      return PushLazy([&value](T* const destination) { ::new (destination) T(value); });
    }
References Job::SPSCQueue< T >::PushLazy().
Pop()
template<typename T > bool Job::SPSCQueue< T >::Pop (T *const out_value) inline
Definition at line 163 of file job_queue.hpp.
    {
      JobAssert(out_value != nullptr, "`out_value` cannot be a nullptr.");
      return PopLazy([out_value](T&& value) { *out_value = std::move(value); });
    }
References JobAssert, and Job::SPSCQueue< T >::PopLazy().
PushLazy()
template<typename T > template<typename CallbackFn > bool Job::SPSCQueue< T >::PushLazy (CallbackFn && callback) inline
Definition at line 172 of file job_queue.hpp.
    {
      const size_type write_index = m_ProducerIndex.load(std::memory_order_relaxed);
      if (IsFull(write_index, m_CachedConsumerIndex))
      {
        m_CachedConsumerIndex = m_ConsumerIndex.load(std::memory_order_acquire);
        if (IsFull(write_index, m_CachedConsumerIndex))
        {
          return false;
        }
      }
      callback(ElementAt(write_index));
      m_ProducerIndex.store(write_index + 1, std::memory_order_release);
      return true;
    }
References Job::SPSCQueue< T >::ElementAt(), Job::SPSCQueue< T >::IsFull(), Job::SPSCQueue< T >::m_CachedConsumerIndex, Job::SPSCQueue< T >::m_ConsumerIndex, and Job::SPSCQueue< T >::m_ProducerIndex.
Referenced by Job::SPSCQueue< T >::Push().
PopLazy()
template<typename T > template<typename CallbackFn > bool Job::SPSCQueue< T >::PopLazy (CallbackFn && callback) inline
Definition at line 192 of file job_queue.hpp.
    {
      const size_type read_index = m_ConsumerIndex.load(std::memory_order_relaxed);
      if (IsEmpty(m_CachedProducerIndex, read_index))
      {
        m_CachedProducerIndex = m_ProducerIndex.load(std::memory_order_acquire);
        if (IsEmpty(m_CachedProducerIndex, read_index))
        {
          return false;
        }
      }
      T* const element = ElementAt(read_index);
      callback(std::move(*element));
      element->~T();
      m_ConsumerIndex.store(read_index + 1, std::memory_order_release);
      return true;
    }
References Job::SPSCQueue< T >::ElementAt(), Job::SPSCQueue< T >::IsEmpty(), Job::SPSCQueue< T >::m_CachedProducerIndex, Job::SPSCQueue< T >::m_ConsumerIndex, and Job::SPSCQueue< T >::m_ProducerIndex.
Referenced by Job::SPSCQueue< T >::Pop().
IsFull()
template<typename T > bool Job::SPSCQueue< T >::IsFull (const size_type head, const size_type tail) const inline private noexcept
Definition at line 214 of file job_queue.hpp.
    {
      return ((head + 1) & m_CapacityMask) == tail;
    }
References Job::SPSCQueue< T >::m_CapacityMask.
Referenced by Job::SPSCQueue< T >::PushLazy().
IsEmpty()
template<typename T > static bool Job::SPSCQueue< T >::IsEmpty (const size_type head, const size_type tail) inline static private noexcept
Definition at line 219 of file job_queue.hpp.
    {
      return head == tail;
    }
Referenced by Job::SPSCQueue< T >::PopLazy().
ElementAt()
template<typename T > T * Job::SPSCQueue< T >::ElementAt (const size_type index) const inline private noexcept
Definition at line 224 of file job_queue.hpp.
    {
      return m_Data + (index & m_CapacityMask);
    }
References Job::SPSCQueue< T >::m_CapacityMask, and Job::SPSCQueue< T >::m_Data.
Referenced by Job::SPSCQueue< T >::PopLazy(), and Job::SPSCQueue< T >::PushLazy().
Member Data Documentation
m_ProducerIndex
template<typename T > atomic_size_type Job::SPSCQueue< T >::m_ProducerIndex private
Definition at line 120 of file job_queue.hpp.
Referenced by Job::SPSCQueue< T >::Initialize(), Job::SPSCQueue< T >::PopLazy(), and Job::SPSCQueue< T >::PushLazy().
m_Padding0
template<typename T > unsigned char Job::SPSCQueue< T >::m_Padding0[k_FalseSharingPadSize - sizeof(m_ProducerIndex)] private
Definition at line 121 of file job_queue.hpp.
m_CachedConsumerIndex
template<typename T > size_type Job::SPSCQueue< T >::m_CachedConsumerIndex private
Definition at line 122 of file job_queue.hpp.
Referenced by Job::SPSCQueue< T >::Initialize(), and Job::SPSCQueue< T >::PushLazy().
m_Padding1
template<typename T > unsigned char Job::SPSCQueue< T >::m_Padding1[k_FalseSharingPadSize - sizeof(m_CachedConsumerIndex)] private
Definition at line 123 of file job_queue.hpp.
m_ConsumerIndex
template<typename T > atomic_size_type Job::SPSCQueue< T >::m_ConsumerIndex private
Definition at line 127 of file job_queue.hpp.
Referenced by Job::SPSCQueue< T >::Initialize(), Job::SPSCQueue< T >::PopLazy(), and Job::SPSCQueue< T >::PushLazy().
m_Padding2
template<typename T > unsigned char Job::SPSCQueue< T >::m_Padding2[k_FalseSharingPadSize - sizeof(m_ConsumerIndex)] private
Definition at line 128 of file job_queue.hpp.
m_CachedProducerIndex
template<typename T > size_type Job::SPSCQueue< T >::m_CachedProducerIndex private
Definition at line 129 of file job_queue.hpp.
Referenced by Job::SPSCQueue< T >::Initialize(), and Job::SPSCQueue< T >::PopLazy().
m_Padding3
template<typename T > unsigned char Job::SPSCQueue< T >::m_Padding3[k_FalseSharingPadSize - sizeof(m_CachedProducerIndex)] private
Definition at line 130 of file job_queue.hpp.
m_Data
template<typename T > T* Job::SPSCQueue< T >::m_Data private
Definition at line 134 of file job_queue.hpp.
Referenced by Job::SPSCQueue< T >::ElementAt(), and Job::SPSCQueue< T >::Initialize().
m_Capacity
template<typename T > size_type Job::SPSCQueue< T >::m_Capacity private
Definition at line 135 of file job_queue.hpp.
Referenced by Job::SPSCQueue< T >::Initialize().
m_CapacityMask
template<typename T > size_type Job::SPSCQueue< T >::m_CapacityMask private
Definition at line 136 of file job_queue.hpp.
Referenced by Job::SPSCQueue< T >::ElementAt(), Job::SPSCQueue< T >::Initialize(), and Job::SPSCQueue< T >::IsFull().
m_Padding4
template<typename T > unsigned char Job::SPSCQueue< T >::m_Padding4[k_FalseSharingPadSize - sizeof(m_Data) - sizeof(m_Capacity) - sizeof(m_CapacityMask)] private
Definition at line 137 of file job_queue.hpp.
The documentation for this class was generated from the following file:
include/concurrent/job_queue.hpp