BluFedora Job System: Job::LockedQueue< T > Class Template Reference
Job::LockedQueue< T > Class Template Reference
#include <job_queue.hpp>
Public Types
using size_type = std::size_t
Public Member Functions
void Initialize (T *const memory_backing, const size_type capacity) noexcept
bool Push (const T &value)
bool Pop (T *const out_value)
Private Member Functions
size_type mask (const size_type raw_index) const noexcept
T * elementAt (const size_type raw_index) const noexcept
Private Attributes
std::mutex m_Lock
T * m_Data
size_type m_Capacity
size_type m_CapacityMask
size_type m_WriteIndex
size_type m_Size
Detailed Description
template<typename T>
class Job::LockedQueue< T >
Definition at line 35 of file job_queue.hpp.
Member Typedef Documentation
size_type
template<typename T > using Job::LockedQueue< T >::size_type = std::size_t
Definition at line 38 of file job_queue.hpp.
Member Function Documentation
Initialize()
template<typename T > void Job::LockedQueue< T >::Initialize (T *const memory_backing, const size_type capacity) inline noexcept
Definition at line 49 of file job_queue.hpp.
    {
      m_Data         = memory_backing;
      m_Capacity     = capacity;
      m_CapacityMask = capacity - 1;
      m_WriteIndex   = 0u;
      m_Size         = 0u;
      JobAssert((m_Capacity & m_CapacityMask) == 0, "Capacity must be a power of 2.");
    }
References JobAssert, Job::LockedQueue< T >::m_Capacity, Job::LockedQueue< T >::m_CapacityMask, Job::LockedQueue< T >::m_Data, Job::LockedQueue< T >::m_Size, and Job::LockedQueue< T >::m_WriteIndex.
Push()
template<typename T > bool Job::LockedQueue< T >::Push (const T & value) inline
Definition at line 60 of file job_queue.hpp.
    {
      const std::lock_guard<std::mutex> guard(m_Lock);
      (void)guard;
      if (m_Size == m_Capacity)
      {
        return false;
      }
      *elementAt(m_WriteIndex++) = value;
      ++m_Size;
      return true;
    }
References Job::LockedQueue< T >::elementAt(), Job::LockedQueue< T >::m_Capacity, Job::LockedQueue< T >::m_Lock, Job::LockedQueue< T >::m_Size, and Job::LockedQueue< T >::m_WriteIndex.
Referenced by Job::TaskSubmit().
Pop()
template<typename T > bool Job::LockedQueue< T >::Pop (T *const out_value) inline
Definition at line 76 of file job_queue.hpp.
    {
      JobAssert(out_value != nullptr, "`out_value` cannot be a nullptr.");
      const std::lock_guard<std::mutex> guard(m_Lock);
      (void)guard;
      if (m_Size == 0u)
      {
        return false;
      }
      *out_value = *elementAt(m_WriteIndex - m_Size);
      --m_Size;
      return true;
    }
References Job::LockedQueue< T >::elementAt(), JobAssert, Job::LockedQueue< T >::m_Lock, Job::LockedQueue< T >::m_Size, and Job::LockedQueue< T >::m_WriteIndex.
mask()
template<typename T > size_type Job::LockedQueue< T >::mask (const size_type raw_index) const inline private noexcept
Definition at line 95 of file job_queue.hpp.
    {
      return raw_index & m_CapacityMask;
    }
References Job::LockedQueue< T >::m_CapacityMask.
Referenced by Job::LockedQueue< T >::elementAt().
elementAt()
template<typename T > T * Job::LockedQueue< T >::elementAt (const size_type raw_index) const inline private noexcept
Definition at line 100 of file job_queue.hpp.
    {
      return m_Data + mask(raw_index);
    }
References Job::LockedQueue< T >::m_Data, and Job::LockedQueue< T >::mask().
Referenced by Job::LockedQueue< T >::Pop(), and Job::LockedQueue< T >::Push().
Member Data Documentation
m_Lock
template<typename T > std::mutex Job::LockedQueue< T >::m_Lock private
Definition at line 41 of file job_queue.hpp.
Referenced by Job::LockedQueue< T >::Pop(), and Job::LockedQueue< T >::Push().
m_Data
template<typename T > T* Job::LockedQueue< T >::m_Data private
Definition at line 42 of file job_queue.hpp.
Referenced by Job::LockedQueue< T >::elementAt(), and Job::LockedQueue< T >::Initialize().
m_Capacity
template<typename T > size_type Job::LockedQueue< T >::m_Capacity private
Definition at line 43 of file job_queue.hpp.
Referenced by Job::LockedQueue< T >::Initialize(), and Job::LockedQueue< T >::Push().
m_CapacityMask
template<typename T > size_type Job::LockedQueue< T >::m_CapacityMask private
Definition at line 44 of file job_queue.hpp.
Referenced by Job::LockedQueue< T >::Initialize(), and Job::LockedQueue< T >::mask().
m_WriteIndex
template<typename T > size_type Job::LockedQueue< T >::m_WriteIndex private
Definition at line 45 of file job_queue.hpp.
Referenced by Job::LockedQueue< T >::Initialize(), Job::LockedQueue< T >::Pop(), and Job::LockedQueue< T >::Push().
m_Size
template<typename T > size_type Job::LockedQueue< T >::m_Size private
Definition at line 46 of file job_queue.hpp.
Referenced by Job::LockedQueue< T >::Initialize(), Job::LockedQueue< T >::Pop(), and Job::LockedQueue< T >::Push().
The documentation for this class was generated from the following file:
include/concurrent/job_queue.hpp