BluFedora Job System: bf::job::detail::ParallelForData< T, S, F > Class Template Reference
bf::job::detail::ParallelForData< T, S, F > Class Template Reference final
#include <bf_job_ext.hpp>
Public Member Functions
ParallelForData (T *data, F job, std::size_t count, S splitter)
T * data () const
F & job ()
std::size_t count () const
S & splitter ()
Private Attributes
CompressedPair< T *, F > m_DataAndJob
CompressedPair< std::size_t, S > m_CountAndSplitter
Detailed Description
template<typename T, typename S, typename F>
class bf::job::detail::ParallelForData< T, S, F >
Definition at line 104 of file bf_job_ext.hpp.
Constructor & Destructor Documentation
ParallelForData()
template<typename T , typename S , typename F > bf::job::detail::ParallelForData< T, S, F >::ParallelForData (T * data, F job, std::size_t count, S splitter) inline
Definition at line 111 of file bf_job_ext.hpp.
                                                                      :
           m_DataAndJob{data, std::forward<F>(job)},
           m_CountAndSplitter{count, std::forward<S>(splitter)}
         {
         }
References bf::job::detail::ParallelForData< T, S, F >::data(), and bf::job::detail::ParallelForData< T, S, F >::job().
Member Function Documentation
data()
template<typename T , typename S , typename F > T* bf::job::detail::ParallelForData< T, S, F >::data () const inline
Definition at line 117 of file bf_job_ext.hpp.
 { return m_DataAndJob.first(); }
References bf::job::detail::ParallelForData< T, S, F >::m_DataAndJob.
Referenced by bf::job::detail::ParallelForData< T, S, F >::ParallelForData().
job()
template<typename T , typename S , typename F > F& bf::job::detail::ParallelForData< T, S, F >::job () inline
Definition at line 118 of file bf_job_ext.hpp.
 { return m_DataAndJob.second(); }
References bf::job::detail::ParallelForData< T, S, F >::m_DataAndJob.
Referenced by bf::job::detail::ParallelForData< T, S, F >::ParallelForData().
count()
template<typename T , typename S , typename F > std::size_t bf::job::detail::ParallelForData< T, S, F >::count () const inline
Definition at line 119 of file bf_job_ext.hpp.
 { return m_CountAndSplitter.first(); }
References bf::job::detail::ParallelForData< T, S, F >::m_CountAndSplitter.
splitter()
template<typename T , typename S , typename F > S& bf::job::detail::ParallelForData< T, S, F >::splitter () inline
Definition at line 120 of file bf_job_ext.hpp.
 { return m_CountAndSplitter.second(); }
References bf::job::detail::ParallelForData< T, S, F >::m_CountAndSplitter.
Member Data Documentation
m_DataAndJob
template<typename T , typename S , typename F > CompressedPair<T*, F> bf::job::detail::ParallelForData< T, S, F >::m_DataAndJob private
Definition at line 107 of file bf_job_ext.hpp.
Referenced by bf::job::detail::ParallelForData< T, S, F >::data(), and bf::job::detail::ParallelForData< T, S, F >::job().
m_CountAndSplitter
template<typename T , typename S , typename F > CompressedPair<std::size_t, S> bf::job::detail::ParallelForData< T, S, F >::m_CountAndSplitter private
Definition at line 108 of file bf_job_ext.hpp.
Referenced by bf::job::detail::ParallelForData< T, S, F >::count(), and bf::job::detail::ParallelForData< T, S, F >::splitter().
The documentation for this class was generated from the following file:
include/bf/job/bf_job_ext.hpp