BluFedora Job System: bf::job Namespace Reference
bf::job Namespace Reference
Namespaces
namespace detail
Classes
struct CountSplitter
struct DataSizeSplitter
struct index_iterator
Range of indices to iterator over.
struct IndexRange
struct JobSystem
struct JobSystemCreateOptions
The runtime configuration for the Job System.
struct StaticCountSplitter
struct StaticDataSizeSplitter
struct Task
A single 'job' to be run by this system.
struct TaskData
A buffer for user-data you can write to, maybe large enough to store task data inline.
struct TaskPool
struct TaskPtr
struct ThreadWorker
Typedefs
using WorkerID = std::uint16_t
The id type of each worker thread.
using TaskFn = void(*)(Task *)
The signature of the type of function for a single Task.
using TaskHandle = std::uint16_t
using TaskHandleType = TaskHandle
using AtomicTaskHandleType = std::atomic< TaskHandle >
using WorkerIDType = WorkerID
using AtomicTaskPtr = std::atomic< TaskPtr >
Enumerations
enum class QueueType : std::uint8_t { NORMAL = 0 , MAIN = 1 , WORKER = 2 }
The priority that you want a task to run at.
Functions
std::size_t numSystemThreads () noexcept
Makes some system calls to grab the number threads / processors on the device. This function can be called by any thread concurrently.
void initialize (const JobSystemCreateOptions &params={0u}) noexcept
Sets up the Job system and creates all the worker threads. The thread that calls 'bfJob::initialize' is considered (and should be) the main thread.
std::uint32_t numWorkers () noexcept
Returns the number of workers created by the system. This function can be called by any thread concurrently.
const char * processorArchitectureName () noexcept
An implementation defined name for the CPU architecture of the device. This function can be called by any thread concurrently.
WorkerID currentWorker () noexcept
The current id of the current thread. This function can be called by any thread concurrently.
void shutdown () noexcept
This will deallocate any memory used by the system and shutdown any threads created by 'bfJob::initialize'.
Task * taskMake (TaskFn function, Task *const parent=nullptr) noexcept
Creates a new Task that should be later submitted by calling 'taskSubmit'.
TaskData taskGetData (Task *const task) noexcept
Returns you the user-data buffer you way write to get data into your TaskFn.
void taskAddContinuation (Task *const self, Task *const continuation) noexcept
A 'continuation' is a task that will be added to a queue after the 'self' Task has finished running.
Task * taskSubmit (Task *const self, QueueType queue=QueueType::NORMAL) noexcept
Submits the task to the specified queue.
template<typename T >
T & taskDataAs (Task *const task) noexcept
Grabs the user-data pointer as the T you specified. No safety is guaranteed, this is just a dumb cast.
template<typename T , typename... Args>
void taskEmplaceData (Task *const task, Args &&... args)
Calls the constructor of T on the user-data buffer.
template<typename T >
void taskSetData (Task *const task, const T &data)
Copies 'data' into the user-data buffer by calling the T copy constructor.
template<typename Closure >
Task * taskMake (Closure &&function, Task *const parent=nullptr)
Creates a new task making a copy of the closure.
void taskIncRef (Task *const task)
Increments the task's ref count preventing it from being garbage collected.
void taskDecRef (Task *const task)
Decrements the task's ref count allow it to be garbage collected.
bool taskIsDone (const Task *const task) noexcept
Returns the done status of the task.
void workerGC ()
Garbage collects tasks allocated on the current worker.
template<typename ConditionFn >
void tickMainQueue (ConditionFn &&condition, const bool run_gc=true) noexcept
Runs tasks from the main queue as long as there are tasks available or condition returns false.
void tickMainQueue (const bool run_gc=true) noexcept
Runs tasks from the main queue until it is empty.
void waitOnTask (const Task *const task) noexcept
Waits until the specified task is done executing. This function will block but do work while being blocked so there is no wasted time.
template<typename F , typename S >
Task * parallel_for (const std::size_t start, const std::size_t count, S &&splitter, F &&fn, Task *parent=nullptr)
Parallel for algorithm, splits the work up recursively spliting based on the splitter passed in.
template<typename T , typename F , typename S >
Task * parallel_for (T *const data, const std::size_t count, S &&splitter, F &&fn, Task *parent=nullptr)
Parallel for algorithm, splits the work up recursively spliting based on the splitter passed in. This version is a helper for array data.
template<typename... F>
Task * parallel_invoke (Task *const parent, F &&... fns)
Invokes each passed in function object in parallel.
static Task * taskPtrToPointer (TaskPtr ptr) noexcept
static void initThreadWorkerID () noexcept
static WorkerID clampThreadCount (WorkerID value, WorkerID min, WorkerID max)
template<typename QueueType >
static void taskSubmitQPushHelper (Task *const self, const WorkerID worker_id, QueueType &queue)
Variables
static constexpr std::size_t k_MainQueueSize = 512
The number of tasks that can be contained in the main queue.
static constexpr std::size_t k_NormalQueueSize = 4096
The number of tasks that can be contained in each worker's high priority queue.
static constexpr std::size_t k_BackgroundQueueSize = 1024
The number of tasks that can be contained in each worker's low priority queue.
static constexpr std::size_t k_MaxThreadsSupported = 32
The maximum number of threads that can be created, this is so that the library can be non dynamically allocating.
static constexpr std::size_t k_CachelineSize = 64u
static constexpr std::size_t k_ExpectedTaskSize = std::max(std::size_t(128u), k_CachelineSize)
static constexpr std::size_t k_MaxTasksPerWorker = k_NormalQueueSize + k_BackgroundQueueSize
static constexpr WorkerID k_MainThreadID = 0
static constexpr QueueType k_InvalidQueueType = QueueType(int(QueueType::WORKER) + 1)
static constexpr TaskHandle NullTaskHandle = std::numeric_limits<TaskHandle>::max()
Class Documentation
bf::job::JobSystemCreateOptions
struct bf::job::JobSystemCreateOptions
The runtime configuration for the Job System.
Definition at line 72 of file bf_job_api.hpp.
Class Members
size_t num_threads Use 0 to indicate using the number of cores available on the system.
bf::job::TaskData
struct bf::job::TaskData
A buffer for user-data you can write to, maybe large enough to store task data inline.
If you store non trivial data remember to manually call it's destructor at the end of the task function.
If you call 'taskEmplaceData' or 'taskSetData' and need to update the data once more be sure to destruct the previous contents correctly if the data stored in the buffer is non trivial.
Definition at line 155 of file bf_job_api.hpp.
Class Members
void * ptr The start of the buffer you may write to.
size_t size The size of the buffer.
Typedef Documentation
WorkerID
using bf::job::WorkerID = typedef std::uint16_t
The id type of each worker thread.
Definition at line 52 of file bf_job_api.hpp.
TaskFn
using bf::job::TaskFn = typedef void (*)(Task*)
The signature of the type of function for a single Task.
Definition at line 53 of file bf_job_api.hpp.
TaskHandle
using bf::job::TaskHandle = typedef std::uint16_t
Definition at line 108 of file bf_job_system.cpp.
TaskHandleType
using bf::job::TaskHandleType = typedef TaskHandle
Definition at line 109 of file bf_job_system.cpp.
AtomicTaskHandleType
using bf::job::AtomicTaskHandleType = typedef std::atomic<TaskHandle>
Definition at line 110 of file bf_job_system.cpp.
WorkerIDType
using bf::job::WorkerIDType = typedef WorkerID
Definition at line 111 of file bf_job_system.cpp.
AtomicTaskPtr
using bf::job::AtomicTaskPtr = typedef std::atomic<TaskPtr>
Definition at line 138 of file bf_job_system.cpp.
Enumeration Type Documentation
QueueType
enum class bf::job::QueueType : std::uint8_t strong
The priority that you want a task to run at.
Enumerator
NORMAL
Tasks in this queue will run on either the main or worker threads.
MAIN
Taskis in this queue will only be run by the main thread.
WORKER
Tasks in this queue will never run on the main thread.
Definition at line 43 of file bf_job_api.hpp.
    {
      NORMAL = 0,
      MAIN   = 1,
      WORKER = 2,
    };
Function Documentation
numSystemThreads()
std::size_t bf::job::numSystemThreads () noexcept
Makes some system calls to grab the number threads / processors on the device. This function can be called by any thread concurrently.
Can be called before and after job system initialization.
Returns
std::size_t The number threads / processors on the computer.
Definition at line 370 of file bf_job_system.cpp.
    {
#if IS_WINDOWS
      SYSTEM_INFO sysinfo;
      GetSystemInfo(&sysinfo);
      return sysinfo.dwNumberOfProcessors;
#elif IS_POSIX
      return sysconf(_SC_NPROCESSORS_ONLN) /* * 2*/;
#elif 0  // FreeBSD, MacOS X, NetBSD, OpenBSD
      nt          mib[4];
      int         numCPU;
      std::size_t len = sizeof(numCPU);
      /* set the mib for hw.ncpu */
      mib[0] = CTL_HW;
      mib[1] = HW_AVAILCPU;  // alternatively, try HW_NCPU;
      /* get the number of CPUs from the system */
      sysctl(mib, 2, &numCPU, &len, NULL, 0);
      if (numCPU < 1)
      {
        mib[1] = HW_NCPU;
        sysctl(mib, 2, &numCPU, &len, NULL, 0);
        if (numCPU < 1)
          numCPU = 1;
      }
      return numCPU;
#elif 0  // HPUX
      return mpctl(MPC_GETNUMSPUS, NULL, NULL);
#elif 0  // IRIX
      return sysconf(_SC_NPROC_ONLN);
#elif 0  // Objective-C (Mac OS X >=10.5 or iOS)
      NSUInteger a = [[NSProcessInfo processInfo] processorCount];
      NSUInteger b = [[NSProcessInfo processInfo] activeProcessorCount];
      return a;
#elif IS_SINGLE_THREADED
      return 1;
#else
      const auto n = std::thread::hardware_concurrency();
      return (n) ? n : 8;
#endif
    }
Referenced by initialize().
initialize()
void bf::job::initialize (const JobSystemCreateOptions & params = {0u}) noexcept
Sets up the Job system and creates all the worker threads. The thread that calls 'bfJob::initialize' is considered (and should be) the main thread.
Parameters
params The customization parameters to initialize the system with.
Definition at line 416 of file bf_job_system.cpp.
    {
      JobAssert(s_NextThreadLocalIndex == 0u, "Job System must be shutdown before it can be initialized again.");
      const WorkerID num_threads = clampThreadCount(WorkerID(params.num_threads ? params.num_threads : numSystemThreads()), WorkerID(1), WorkerID(k_MaxThreadsSupported));
      s_JobCtx.num_workers = num_threads;
#if JOB_SYS_DETERMINISTIC_JOB_STEAL_RNG
      constexpr std::uint64_t random_seed = 0u;
#else
      const std::uint64_t random_seed = static_cast<std::uint64_t>(rand());
#endif
      s_JobCtx.is_running = true;
      for (WorkerID i = 0; i < num_threads; ++i)
      {
        ThreadWorker* const worker = new (s_JobCtx.workers() + i) ThreadWorker();
        worker->start(i, random_seed);
      }
      s_IsFullyInitialized = true;
#if IS_WINDOWS
      SYSTEM_INFO sysinfo;
      GetSystemInfo(&sysinfo);
      switch (sysinfo.wProcessorArchitecture)
      {
        case PROCESSOR_ARCHITECTURE_AMD64:
        {
          s_JobCtx.sys_arch_str = "x64 (Intel or AMD)";
          break;
        }
        case PROCESSOR_ARCHITECTURE_ARM:
        {
          s_JobCtx.sys_arch_str = "ARM";
          break;
        }
        case PROCESSOR_ARCHITECTURE_ARM64:
        {
          s_JobCtx.sys_arch_str = "ARM64";
          break;
        }
        case PROCESSOR_ARCHITECTURE_IA64:
        {
          s_JobCtx.sys_arch_str = "Intel Itanium-Based";
          break;
        }
        case PROCESSOR_ARCHITECTURE_INTEL:
        {
          s_JobCtx.sys_arch_str = "Intel x86";
          break;
        }
        case PROCESSOR_ARCHITECTURE_UNKNOWN:
        default:
        {
          s_JobCtx.sys_arch_str = "Unknown Arch";
          break;
        }
      }
#endif
    }
References clampThreadCount(), JobAssert, k_MaxThreadsSupported, numSystemThreads(), and bf::job::ThreadWorker::start().
numWorkers()
std::uint32_t bf::job::numWorkers () noexcept
Returns the number of workers created by the system. This function can be called by any thread concurrently.
Returns
std::size_t The number of workers created by the system.
Definition at line 482 of file bf_job_system.cpp.
    {
      return s_JobCtx.num_workers;
    }
Referenced by currentWorker(), and taskSubmit().
processorArchitectureName()
const char * bf::job::processorArchitectureName () noexcept
An implementation defined name for the CPU architecture of the device. This function can be called by any thread concurrently.
Returns
const char* Nul terminated name for the CPU architecture of the device.
Definition at line 487 of file bf_job_system.cpp.
    {
      return s_JobCtx.sys_arch_str;
    }
currentWorker()
WorkerID bf::job::currentWorker () noexcept
The current id of the current thread. This function can be called by any thread concurrently.
Returns
WorkerID The current id of the current thread.
Definition at line 492 of file bf_job_system.cpp.
    {
      JobAssert(WorkerID(s_ThreadLocalIndex) < numWorkers(), "This thread was not created by the job system.");
      return WorkerID(s_ThreadLocalIndex);
    }
References JobAssert, and numWorkers().
Referenced by bf::job::detail::mainQueueRunTask(), bf::job::ThreadWorker::start(), taskMake(), taskSubmit(), waitOnTask(), and workerGC().
shutdown()
void bf::job::shutdown () noexcept
This will deallocate any memory used by the system and shutdown any threads created by 'bfJob::initialize'.
This function may only be called by the main thread.
Definition at line 498 of file bf_job_system.cpp.
    {
      JobAssert(s_NextThreadLocalIndex != 0u, "Job System must be initialized before it can be shutdown.");
      s_JobCtx.is_running = false;
      const std::uint32_t num_workers = s_JobCtx.num_workers;
      // Allow one last update loop to allow them to end.
      s_JobCtx.wakeUpAllWorkers();
      for (std::uint32_t i = 0; i < num_workers; ++i)
      {
        ThreadWorker* const worker = s_JobCtx.workers() + i;
        if (i != k_MainThreadID)
        {
          worker->stop();
        }
        worker->~ThreadWorker();
      }
      s_NextThreadLocalIndex = 0u;
      s_IsFullyInitialized   = false;
    }
References JobAssert, k_MainThreadID, and bf::job::ThreadWorker::stop().
taskMake() [1/2]
Task * bf::job::taskMake (TaskFn function, Task *const parent = nullptr) noexcept
Creates a new Task that should be later submitted by calling 'taskSubmit'.
Parameters
function The function you want run by the scheduler.
parent An optional parent Task used in conjunction with 'waitOnTask' to force dependencies.
Returns
Task* The newly created task.
Definition at line 525 of file bf_job_system.cpp.
    {
      const WorkerID worker_id = currentWorker();
      ThreadWorker* const worker = s_JobCtx.workers() + worker_id;
      if (worker->num_allocated_tasks == k_MaxTasksPerWorker)
      {
        s_JobCtx.wakeUpAllWorkers();
        // While we cannot allocate do some work.
        worker->garbageCollectAllocatedTasks();
        while (worker->num_allocated_tasks == k_MaxTasksPerWorker)
        {
          worker->run(worker_id);
          worker->garbageCollectAllocatedTasks();
        }
      }
      JobAssert(worker->num_allocated_tasks < k_MaxTasksPerWorker, "Too many tasks allocated.");
      Task* const      task     = worker->task_memory.allocate(worker_id, function, parent ? parent->toTaskPtr() : TaskPtr{NullTaskHandle, NullTaskHandle});
      const TaskHandle task_hdl = TaskHandle(worker->task_memory.indexOf(task));
      if (parent)
      {
        parent->num_unfinished_tasks.fetch_add(1u);
      }
      worker->allocated_tasks[worker->num_allocated_tasks++] = task_hdl;
      ++task->ref_count;
      return task;
    }
References bf::job::TaskPool< k_MaxTask >::allocate(), bf::job::ThreadWorker::allocated_tasks, currentWorker(), bf::job::ThreadWorker::garbageCollectAllocatedTasks(), bf::job::TaskPool< k_MaxTask >::indexOf(), JobAssert, k_MaxTasksPerWorker, bf::job::ThreadWorker::num_allocated_tasks, bf::job::Task::parent, bf::job::Task::ref_count, bf::job::ThreadWorker::run(), and bf::job::ThreadWorker::task_memory.
Referenced by parallel_for(), parallel_invoke(), and taskMake().
taskGetData()
TaskData bf::job::taskGetData (Task *const task) noexcept
Returns you the user-data buffer you way write to get data into your TaskFn.
Parameters
task The task whose user-data you want to grab.
Returns
TaskData The user-data buffer you may read and write.
Definition at line 560 of file bf_job_system.cpp.
    {
      const std::size_t user_data_start = sizeof(task->padding) - task->user_storage_size;
      return {task->padding.data() + user_data_start, task->user_storage_size};
    }
Referenced by taskDataAs(), and taskEmplaceData().
taskAddContinuation()
void bf::job::taskAddContinuation (Task *const self, Task *const continuation) noexcept
A 'continuation' is a task that will be added to a queue after the 'self' Task has finished running.
Continuations will be added to the same queue as the queue from the task that submits it.
Parameters
self The task to add the 'continuation' to.
continuation The Task to run after 'self' has finished. This task must not have already been submitted to a queue.
Definition at line 566 of file bf_job_system.cpp.
    {
      JobAssert(self->q_type == k_InvalidQueueType, "The task should not have already been submitted to a queue.");
      JobAssert(continuation->q_type == k_InvalidQueueType, "A continuation must not have already been submitted to a queue.");
      JobAssert(continuation->next_continuation.isNull(), "A continuation must not have already been added to another task.");
      const TaskPtr new_head = continuation->toTaskPtr();
      TaskPtr       expected_head;
      do
      {
        expected_head                   = self->first_continuation.load();
        continuation->next_continuation = expected_head;
      } while (!std::atomic_compare_exchange_weak(&self->first_continuation, &expected_head, new_head));
    }
References JobAssert, and k_InvalidQueueType.
taskSubmit()
Task * bf::job::taskSubmit (Task *const self, QueueType queue = QueueType::NORMAL) noexcept
Submits the task to the specified queue.
The Task is not required to have been created on the same thread that submits.
You may now wait on this task using 'waitOnTask'.
Parameters
self The task to submit.
queue The queue you want the task to run on.
Returns
Task* Returns the task passed in.
Definition at line 596 of file bf_job_system.cpp.
    {
      const WorkerID num_workers = numWorkers();
      const WorkerID worker_id   = currentWorker();
      // If we only have one thread running using the working queue is invalid.
      if (num_workers == 1u && queue == QueueType::WORKER)
      {
        queue = QueueType::NORMAL;
      }
      JobAssert(self->q_type == k_InvalidQueueType, "A task cannot be submitted to a queue multiple times.");
      ThreadWorker* const worker = s_JobCtx.workers() + worker_id;
      self->q_type = queue;
      switch (queue)
      {
        case QueueType::NORMAL:
        {
          taskSubmitQPushHelper(self, worker_id, worker->hi_queue);
          break;
        }
        case QueueType::MAIN:
        {
          taskSubmitQPushHelper(self, worker_id, s_JobCtx.main_queue);
          break;
        }
        case QueueType::WORKER:
        {
          taskSubmitQPushHelper(self, worker_id, worker->bg_queue);
          break;
        }
      }
      if (queue != QueueType::MAIN)
      {
        const std::int32_t num_pending_jobs = s_JobCtx.num_available_jobs.fetch_add(1);
        if (num_pending_jobs >= num_workers)
        {
          s_JobCtx.wakeUpAllWorkers();
        }
        else
        {
          s_JobCtx.wakeUpOneWorker();
        }
      }
      return self;
    }
References bf::job::ThreadWorker::bg_queue, currentWorker(), bf::job::ThreadWorker::hi_queue, JobAssert, k_InvalidQueueType, MAIN, NORMAL, numWorkers(), taskSubmitQPushHelper(), and WORKER.
Referenced by bf::job::Task::onFinish(), parallel_for(), and parallel_invoke().
taskDataAs()
template<typename T > T & bf::job::taskDataAs (Task *const task) noexcept
Grabs the user-data pointer as the T you specified. No safety is guaranteed, this is just a dumb cast.
Template Parameters
T The type you want to receive the user-data buffer as.
Parameters
task The task whose data you are retrieving.
Returns
T& The user-data buffer casted as a T.
Definition at line 410 of file bf_job_api.hpp.
    {
      detail::checkTaskDataSize(task, sizeof(T));
      return *static_cast<T*>(taskGetData(task).ptr);
    }
References bf::job::detail::checkTaskDataSize(), bf::job::TaskData::ptr, and taskGetData().
taskEmplaceData()
template<typename T , typename... Args> void bf::job::taskEmplaceData (Task *const task, Args &&... args)
Calls the constructor of T on the user-data buffer.
Template Parameters
T The type of T you want constructed in-place into the user-data buffer.
Args The Argument types passed into the T constructor.
Parameters
task The task whose user-data buffer is affected.
args The arguments passed into the constructor of the user-data buffer casted as a T.
Definition at line 417 of file bf_job_api.hpp.
    {
      detail::checkTaskDataSize(task, sizeof(T));
      new (taskGetData(task).ptr) T(std::forward<Args>(args)...);
    }
References bf::job::detail::checkTaskDataSize(), bf::job::TaskData::ptr, and taskGetData().
taskSetData()
template<typename T > void bf::job::taskSetData (Task *const task, const T & data)
Copies 'data' into the user-data buffer by calling the T copy constructor.
Template Parameters
T The data type that will be emplaced into the user-data buffer.
Parameters
task The task whose user-data buffer is affected.
data The data copied into the user-data buffer.
Definition at line 424 of file bf_job_api.hpp.
    {
      taskEmplaceData<T>(task, data);
    }
taskMake() [2/2]
template<typename Closure > Task * bf::job::taskMake (Closure && function, Task *const parent = nullptr)
Creates a new task making a copy of the closure.
Template Parameters
Closure The type of the callable.
Parameters
function The non pointer callable you want to store.
parent An optional parent Task used in conjunction with 'waitOnTask' to force dependencies.
Returns
Task* The newly created task.
Definition at line 430 of file bf_job_api.hpp.
    {
      Task* const task = taskMake(
       +[](Task* task) {
         Closure& function = *static_cast<Closure*>(detail::taskPaddingStart(task));
         function(task);
         function.~Closure();
       },
       parent);
      taskEmplaceData<Closure>(task, std::forward<Closure>(function));
      detail::taskUsePadding(task, sizeof(Closure));
      return task;
    }
References taskMake(), bf::job::detail::taskPaddingStart(), and bf::job::detail::taskUsePadding().
taskIncRef()
void bf::job::taskIncRef (Task *const task)
Increments the task's ref count preventing it from being garbage collected.
This function should be called before taskSubmit.
Parameters
task The task's who's ref count should be incremented.
Definition at line 649 of file bf_job_system.cpp.
    {
      const auto old_ref_count = task->ref_count.fetch_add(1, std::memory_order_relaxed);
      JobAssert(old_ref_count >= 1u || task->q_type == k_InvalidQueueType, "First call to taskIncRef should not happen after the task has been submitted.");
    }
References JobAssert, k_InvalidQueueType, bf::job::Task::q_type, and bf::job::Task::ref_count.
taskDecRef()
void bf::job::taskDecRef (Task *const task)
Decrements the task's ref count allow it to be garbage collected.
Parameters
task The task's who's ref count should be decremented.
Definition at line 656 of file bf_job_system.cpp.
    {
      const auto old_ref_count = task->ref_count.fetch_sub(1, std::memory_order_relaxed);
      JobAssert(old_ref_count >= 0, "taskDecRef: Called too many times.");
      (void)old_ref_count;
    }
References JobAssert, and bf::job::Task::ref_count.
taskIsDone()
bool bf::job::taskIsDone (const Task *const task) noexcept
Returns the done status of the task.
This is only safe to call after submiting the task if you have an active reference to the task through a call to taskIncRef.
Parameters
task The task to check whether or not it's done.
Returns
true - The task is done running. false - The task is still running.
See also
taskIncRef
Definition at line 664 of file bf_job_system.cpp.
    {
      return task->num_unfinished_tasks.load() == -1;
    }
Referenced by waitOnTask().
workerGC()
void bf::job::workerGC ()
Garbage collects tasks allocated on the current worker.
Definition at line 669 of file bf_job_system.cpp.
    {
      const WorkerID worker_id = currentWorker();
      ThreadWorker& worker = s_JobCtx.workers()[worker_id];
      worker.garbageCollectAllocatedTasks();
    }
References currentWorker(), and bf::job::ThreadWorker::garbageCollectAllocatedTasks().
Referenced by tickMainQueue().
tickMainQueue() [1/2]
template<typename ConditionFn > void bf::job::tickMainQueue (ConditionFn && condition, const bool run_gc = true) noexcept
Runs tasks from the main queue as long as there are tasks available or condition returns false.
This function is not required to be called since the main queue will be evaluated during other calls to this API but allows for an easy way to flush the main queue guaranteeing a minimum latency.
Template Parameters
ConditionFn The type of the callable. Must be callable like: bool operator()(void);.
Parameters
condition The function object indicating if the main queue should continue being evaluated. Will be called after a task has been completed.
run_gc Whether or not the garbage collector should be run after running tasks.
Warning
Must only be called from the main thread.
Definition at line 359 of file bf_job_api.hpp.
    {
      do
      {
        if (!detail::mainQueueRunTask())
        {
          break;
        }
      } while (condition());
      if (run_gc)
      {
        workerGC();
      }
    }
References bf::job::detail::mainQueueRunTask(), and workerGC().
Referenced by tickMainQueue().
tickMainQueue() [2/2]
void bf::job::tickMainQueue (const bool run_gc = true) inline noexcept
Runs tasks from the main queue until it is empty.
This function is not required to be called since the main queue will be evaluated during other calls to this API but allows for an easy way to flush the main queue guaranteeing a minimum latency.
Parameters
run_gc Whether or not the garbage collector should be run after running tasks.
Warning
Must only be called from the main thread.
Definition at line 388 of file bf_job_api.hpp.
    {
      tickMainQueue([]() { return true; }, run_gc);
    }
References tickMainQueue().
waitOnTask()
void bf::job::waitOnTask (const Task *const task) noexcept
Waits until the specified task is done executing. This function will block but do work while being blocked so there is no wasted time.
You may only call this function with a task created on the current 'Worker'.
It is a logic error to call this function on a task that has not been taskSubmit'd.
Parameters
task The task to wait to finish executing.
Definition at line 678 of file bf_job_system.cpp.
    {
      const WorkerID worker_id = currentWorker();
      JobAssert(task->q_type != k_InvalidQueueType, "The Task must be submitted to a queue before you wait on it.");
      JobAssert(task->owning_worker == worker_id, "You may only call this function with a task created on the current 'Worker'.");
      s_JobCtx.wakeUpAllWorkers();
      ThreadWorker& worker = s_JobCtx.workers()[worker_id];
      while (!taskIsDone(task))
      {
        worker.run(worker_id);
      }
    }
References currentWorker(), JobAssert, k_InvalidQueueType, bf::job::ThreadWorker::run(), and taskIsDone().
parallel_for() [1/2]
template<typename F , typename S > Task * bf::job::parallel_for (const std::size_t start, const std::size_t count, S && splitter, F && fn, Task * parent = nullptr)
Parallel for algorithm, splits the work up recursively spliting based on the splitter passed in.
Assumes all callables passed in are thread safe.
Template Parameters
F Type of function object passed in. Must be callable like: fn(Task* task, IndexRange index_range)
S Callable splitter, must be callable like: splitter(std::size_t count)
Parameters
start Start index for the range to be parallelized.
count start + count defines the end range.
splitter Callable splitter, must be callable like: splitter(std::size_t count)
fn Function object must be callable like: fn(Task* task, IndexRange index_range)
parent Parent task to add this task as a child of.
Returns
The new task holding the work of the parallel for.
Definition at line 115 of file bf_job_ext.hpp.
    {
      return taskMake(
       [=, splitter = std::move(splitter), fn = std::move(fn)](Task* const task) {
         if (count > 1u && splitter(count))
         {
           const std::size_t left_count    = count / 2;
           const std::size_t right_count   = count - left_count;
           const QueueType   parent_q_type = detail::taskQType(task);
           if (left_count)
           {
             taskSubmit(parallel_for(start, left_count, splitter, fn, task), parent_q_type);
           }
           if (right_count)
           {
             taskSubmit(parallel_for(start + left_count, right_count, splitter, fn, task), parent_q_type);
           }
         }
         else
         {
           fn(task, IndexRange{start, start + count});
         }
       },
       parent);
    }
References parallel_for(), taskMake(), bf::job::detail::taskQType(), and taskSubmit().
Referenced by parallel_for().
parallel_for() [2/2]
template<typename T , typename F , typename S > Task * bf::job::parallel_for (T *const data, const std::size_t count, S && splitter, F && fn, Task * parent = nullptr)
Parallel for algorithm, splits the work up recursively spliting based on the splitter passed in. This version is a helper for array data.
Assumes all callables passed in are thread safe.
Template Parameters
T Type of the array to process.
F Type of function object passed in. Must be callable like: fn(Task* task, IndexRange index_range)
S Callable splitter, must be callable like: splitter(std::size_t count)
Parameters
data The start of the array to process.
count The number of elements in the data array.
splitter Callable splitter, must be callable like: splitter(std::size_t count)
fn Function object must be callable like: fn(Task* task, IndexRange index_range)
parent Parent task to add this task as a child of.
Returns
The new task holding the work of the parallel for.
Definition at line 179 of file bf_job_ext.hpp.
    {
      return parallel_for(
       std::size_t(0), count, std::move(splitter), [data, fn = std::move(fn)](Task* const task, const IndexRange index_range) {
         fn(task, data + index_range.idx_bgn, index_range.length());
       },
       parent);
    }
References bf::job::IndexRange::idx_bgn, bf::job::IndexRange::length(), and parallel_for().
parallel_invoke()
template<typename... F> Task * bf::job::parallel_invoke (Task *const parent, F &&... fns)
Invokes each passed in function object in parallel.
Template Parameters
...F The function objects types. Must be callable like: fn(Task* task)
Parameters
parent Parent task to add this task as a child of.
...fns Function objects must be callable like: fn(Task* task)
Returns
The new task holding the work of the parallel invoke.
Definition at line 206 of file bf_job_ext.hpp.
    {
      return taskMake(
       [=](Task* const parent_task) mutable {
         const QueueType parent_q_type = detail::taskQType(parent_task);
         (taskSubmit(taskMake(std::move(fns), parent_task), parent_q_type), ...);
       },
       parent);
    }
References taskMake(), bf::job::detail::taskQType(), and taskSubmit().
taskPtrToPointer()
static Task * bf::job::taskPtrToPointer (TaskPtr ptr) static noexcept
Definition at line 975 of file bf_job_system.cpp.
    {
      if (!ptr.isNull())
      {
        ThreadWorker* const worker = s_JobCtx.workers() + ptr.worker_id;
        Task* const         result = worker->task_memory.fromIndex(ptr.task_index);
        JobAssert(ptr.worker_id == result->owning_worker, "Corrupted worker ID.");
        return result;
      }
      return nullptr;
    }
References bf::job::TaskPool< k_MaxTask >::fromIndex(), JobAssert, bf::job::Task::owning_worker, and bf::job::ThreadWorker::task_memory.
Referenced by bf::job::detail::mainQueueRunTask(), bf::job::Task::onFinish(), and bf::job::ThreadWorker::run().
initThreadWorkerID()
static void bf::job::initThreadWorkerID () static noexcept
Definition at line 990 of file bf_job_system.cpp.
    {
      s_ThreadLocalIndex = s_NextThreadLocalIndex++;
      JobAssert(s_ThreadLocalIndex < s_NextThreadLocalIndex, "Something went very wrong if this is not true.");
    }
References JobAssert.
Referenced by bf::job::ThreadWorker::start().
clampThreadCount()
static WorkerID bf::job::clampThreadCount (WorkerID value, WorkerID min, WorkerID max) static
Definition at line 365 of file bf_job_system.cpp.
    {
      return std::min(std::max(min, value), max);
    }
Referenced by initialize().
taskSubmitQPushHelper()
template<typename QueueType > static void bf::job::taskSubmitQPushHelper (Task *const self, const WorkerID worker_id, QueueType & queue) static
Definition at line 583 of file bf_job_system.cpp.
    {
      ThreadWorker* const worker   = s_JobCtx.workers() + worker_id;
      const TaskPtr       task_ptr = self->toTaskPtr();
      // Loop until we have successfully pushed to the queue.
      while (!queue.push(task_ptr))
      {
        // If we could not push to the queues then just do some work.
        worker->run(worker_id);
      }
    }
References bf::job::ThreadWorker::run().
Referenced by taskSubmit().
Variable Documentation
k_MainQueueSize
constexpr std::size_t bf::job::k_MainQueueSize = 512 static constexpr
The number of tasks that can be contained in the main queue.
Definition at line 32 of file bf_job_config.hpp.
k_NormalQueueSize
constexpr std::size_t bf::job::k_NormalQueueSize = 4096 static constexpr
The number of tasks that can be contained in each worker's high priority queue.
Definition at line 33 of file bf_job_config.hpp.
k_BackgroundQueueSize
constexpr std::size_t bf::job::k_BackgroundQueueSize = 1024 static constexpr
The number of tasks that can be contained in each worker's low priority queue.
Definition at line 34 of file bf_job_config.hpp.
k_MaxThreadsSupported
constexpr std::size_t bf::job::k_MaxThreadsSupported = 32 static constexpr
The maximum number of threads that can be created, this is so that the library can be non dynamically allocating.
Definition at line 35 of file bf_job_config.hpp.
Referenced by initialize(), and bf::job::ThreadWorker::randomWorker().
k_CachelineSize
constexpr std::size_t bf::job::k_CachelineSize = 64u static constexpr
Definition at line 94 of file bf_job_system.cpp.
k_ExpectedTaskSize
constexpr std::size_t bf::job::k_ExpectedTaskSize = std::max(std::size_t(128u), k_CachelineSize) static constexpr
Definition at line 97 of file bf_job_system.cpp.
k_MaxTasksPerWorker
constexpr std::size_t bf::job::k_MaxTasksPerWorker = k_NormalQueueSize + k_BackgroundQueueSize static constexpr
Definition at line 98 of file bf_job_system.cpp.
Referenced by taskMake().
k_MainThreadID
constexpr WorkerID bf::job::k_MainThreadID = 0 static constexpr
Definition at line 99 of file bf_job_system.cpp.
Referenced by bf::job::ThreadWorker::run(), shutdown(), and bf::job::ThreadWorker::start().
k_InvalidQueueType
constexpr QueueType bf::job::k_InvalidQueueType = QueueType(int(QueueType::WORKER) + 1) static constexpr
Definition at line 100 of file bf_job_system.cpp.
Referenced by taskAddContinuation(), taskIncRef(), taskSubmit(), and waitOnTask().
NullTaskHandle
constexpr TaskHandle bf::job::NullTaskHandle = std::numeric_limits<TaskHandle>::max() static constexpr
Definition at line 113 of file bf_job_system.cpp.
Referenced by bf::job::TaskPtr::isNull().