BluFedora Job System: bf::job::detail Namespace Reference
bf::job::detail Namespace Reference
Classes
struct CompressedPair
struct CompressedPair< T0, T1, false, false >
struct CompressedPair< T0, T1, false, true >
struct CompressedPair< T0, T1, true, false >
struct CompressedPair< T0, T1, true, true >
class ParallelForData
Functions
void checkTaskDataSize (std::size_t data_size) noexcept
QueueType taskQType (const Task *task) noexcept
template<typename T , typename F , typename S >
void parallel_for_impl (Task *job)
Variables
template<typename T >
constexpr bool is_empty_base_candidate = std::is_empty_v<T> && !std::is_final_v<T>
Class Documentation
bf::job::detail::CompressedPair
struct bf::job::detail::CompressedPair
template<typename T0, typename T1, bool is_T0_Empty = is_empty_base_candidate<T0>, bool is_T1_Empty = is_empty_base_candidate<T1>>
struct bf::job::detail::CompressedPair< T0, T1, is_T0_Empty, is_T1_Empty >
Definition at line 32 of file bf_job_ext.hpp.
Function Documentation
checkTaskDataSize()
void bf::job::detail::checkTaskDataSize (std::size_t data_size) noexcept
Definition at line 227 of file bf_job_system.cpp.
     {
       assert(data_size <= k_TaskPaddingDataSize && "Attempting to store an object too large for this task.");
       (void)data_size;
     }
References bf::job::k_TaskPaddingDataSize.
Referenced by bf::job::taskDataAs(), and bf::job::taskEmplaceData().
taskQType()
QueueType bf::job::detail::taskQType (const Task * task) noexcept
Definition at line 233 of file bf_job_system.cpp.
     {
       return task->q_type;
     }
Referenced by parallel_for_impl().
parallel_for_impl()
template<typename T , typename F , typename S > void bf::job::detail::parallel_for_impl (Task * job)
Definition at line 187 of file bf_job_ext.hpp.
       {
         using ParallelForDataType = ParallelForData<T, S, F>;
         ParallelForDataType& data       = taskDataAs<ParallelForDataType>(task);
         F&                   custom_f   = data.job();
         const std::size_t    data_count = data.count();
         if (data.splitter()(data_count))
         {
           const std::size_t left_count    = data_count / 2;
           const std::size_t right_count   = data_count - left_count;
           const QueueType   parent_q_type = taskQType(task);
           if (left_count)
           {
             Task* const left_task = taskMake(&detail::parallel_for_impl<T, F, S>, task);
             taskEmplaceData<ParallelForDataType>(left_task, data.data(), custom_f, left_count, data.splitter());
             taskSubmit(left_task, parent_q_type);
           }
           if (right_count)
           {
             Task* const right_task = taskMake(&detail::parallel_for_impl<T, F, S>, task);
             taskEmplaceData<ParallelForDataType>(right_task, data.data() + left_count, custom_f, right_count, data.splitter());
             taskSubmit(right_task, parent_q_type);
           }
         }
         else
         {
           custom_f(data.data(), data.count());
         }
         data.~ParallelForDataType();
       }
References bf::job::taskMake(), taskQType(), and bf::job::taskSubmit().
Variable Documentation
is_empty_base_candidate
template<typename T > constexpr bool bf::job::detail::is_empty_base_candidate = std::is_empty_v<T> && !std::is_final_v<T> inline constexpr
Definition at line 29 of file bf_job_ext.hpp.