BluFedora Job System: Job::detail Namespace Reference
Job::detail Namespace Reference
Functions
QueueType taskQType (const Task *task) noexcept
void * taskGetPrivateUserData (Task *const task, const std::size_t alignment) noexcept
void * taskReservePrivateUserData (Task *const task, const std::size_t num_bytes, const std::size_t alignment) noexcept
bool mainQueueTryRunTask (void) noexcept
template<typename Closure >
static void taskLambdaWrapper (Task *const task)
void assertHandler (const bool condition, const char *const filename, const int line_number, const char *const msg)
Function Documentation
taskQType()
QueueType Job::detail::taskQType (const Task * task) noexcept
Definition at line 1173 of file job_system.cpp.
{
  return task->q_type;
}
Referenced by Job::ParallelFor(), and Job::ParallelInvoke().
taskGetPrivateUserData()
void * Job::detail::taskGetPrivateUserData (Task *const task, const std::size_t alignment) noexcept
Definition at line 1178 of file job_system.cpp.
{
  return AlignPointer(task->padding.data(), alignment);
}
Referenced by taskLambdaWrapper().
taskReservePrivateUserData()
void * Job::detail::taskReservePrivateUserData (Task *const task, const std::size_t num_bytes, const std::size_t alignment) noexcept
Definition at line 1183 of file job_system.cpp.
{
  const Byte* const user_storage_start      = task->padding.data() + task->user_data_start;
  const Byte* const user_storage_end        = &*task->padding.end();
  Byte* const       requested_storage_start = static_cast<Byte*>(AlignPointer(user_storage_start, alignment));
  const Byte* const requested_storage_end   = requested_storage_start + num_bytes;
  JobAssert(requested_storage_end <= user_storage_end, "Cannot store object within the task's user storage. ");
  task->user_data_start = static_cast<std::uint8_t>(requested_storage_end - task->padding.data());
  return requested_storage_start;
}
References JobAssert.
Referenced by Job::TaskMake().
mainQueueTryRunTask()
bool Job::detail::mainQueueTryRunTask (void) noexcept
Definition at line 1197 of file job_system.cpp.
{
  JobAssert(CurrentWorker() == k_MainThreadID, "Must only be called by main thread.");
  TaskPtr task_ptr;
  if (g_JobSystem->main_queue.Pop(&task_ptr))
  {
    Task* const task = task::TaskPtrToPointer(task_ptr);
    task::RunTaskFunction(task);
    return true;
  }
  return false;
}
References Job::CurrentWorker(), g_JobSystem, JobAssert, Job::k_MainThreadID, and Job::JobSystemContext::main_queue.
Referenced by Job::TickMainQueue().
taskLambdaWrapper()
template<typename Closure > static void Job::detail::taskLambdaWrapper (Task *const task) static
Definition at line 490 of file job_api.hpp.
    {
      Closure& function = *static_cast<Closure*>(detail::taskGetPrivateUserData(task, alignof(Closure)));
      function(task);
      function.~Closure();
    }
References taskGetPrivateUserData().
assertHandler()
void Job::detail::assertHandler (const bool condition, const char *const filename, const int line_number, const char *const msg)