BluFedora Job System: Job::TaskPool< k_MaxTask > Struct Template Reference
Job::TaskPool< k_MaxTask > Struct Template Reference
Classes
union TaskMemoryBlock
Public Member Functions
TaskPool ()
Task * allocate (WorkerID worker, TaskFn fn, TaskPtr parent)
std::size_t indexOf (const Task *const task) const
Task * fromIndex (const std::size_t idx)
void deallocate (Task *const task)
Public Attributes
TaskMemoryBlock memory [k_MaxTask]
TaskMemoryBlock * current_block
Static Public Attributes
static constexpr std::size_t k_MaxTaskMinusOne = k_MaxTask - 1u
Detailed Description
template<std::size_t k_MaxTask>
struct Job::TaskPool< k_MaxTask >
Definition at line 188 of file bf_job_system.cpp.
Class Documentation
Job::TaskPool::TaskMemoryBlock
union Job::TaskPool::TaskMemoryBlock
template<std::size_t k_MaxTask>
union Job::TaskPool< k_MaxTask >::TaskMemoryBlock
Definition at line 194 of file bf_job_system.cpp.
Class Members
TaskMemoryBlock * next
aligned_storage_t< sizeof(Task), alignof(Task)> storage
Constructor & Destructor Documentation
TaskPool()
template<std::size_t k_MaxTask> Job::TaskPool< k_MaxTask >::TaskPool () inline
Definition at line 203 of file bf_job_system.cpp.
    {
      for (std::size_t i = 0u; i < k_MaxTaskMinusOne; ++i)
      {
        memory[i].next = &memory[i + 1u];
      }
      memory[k_MaxTaskMinusOne].next = nullptr;
      current_block = &memory[0];
    }
References Job::TaskPool< k_MaxTask >::TaskMemoryBlock::next.
Member Function Documentation
allocate()
template<std::size_t k_MaxTask> Task * Job::TaskPool< k_MaxTask >::allocate (WorkerID worker, TaskFn fn, TaskPtr parent) inline
Definition at line 214 of file bf_job_system.cpp.
    {
      TaskMemoryBlock* const result = std::exchange(current_block, current_block->next);
      JobAssert(result != nullptr, "Allocation failure.");
      return new (result) Task(worker, fn, parent);
    }
References Job::Task::fn, JobAssert, Job::TaskPool< k_MaxTask >::TaskMemoryBlock::next, Job::Task::parent, and Job::Task::Task().
Referenced by Job::taskMake().
indexOf()
template<std::size_t k_MaxTask> std::size_t Job::TaskPool< k_MaxTask >::indexOf (const Task *const task) const inline
Definition at line 223 of file bf_job_system.cpp.
    {
      const TaskMemoryBlock* const block = reinterpret_cast<const TaskMemoryBlock*>(task);
      JobAssert(block >= memory && block < (memory + k_MaxTask), "Invalid task pointer passed in.");
      return block - memory;
    }
References JobAssert.
Referenced by Job::taskMake().
fromIndex()
template<std::size_t k_MaxTask> Task * Job::TaskPool< k_MaxTask >::fromIndex (const std::size_t idx) inline
Definition at line 232 of file bf_job_system.cpp.
    {
      JobAssert(idx < k_MaxTask, "Invalid index.");
      return reinterpret_cast<Task*>(&memory[idx].storage);
    }
References JobAssert, and Job::TaskPool< k_MaxTask >::TaskMemoryBlock::storage.
Referenced by Job::ThreadWorker::garbageCollectAllocatedTasks(), and Job::taskPtrToPointer().
deallocate()
template<std::size_t k_MaxTask> void Job::TaskPool< k_MaxTask >::deallocate (Task *const task) inline
Definition at line 239 of file bf_job_system.cpp.
    {
      task->~Task();
      TaskMemoryBlock* const block = reinterpret_cast<TaskMemoryBlock*>(task);
      block->next = std::exchange(current_block, block);
    }
References Job::TaskPool< k_MaxTask >::TaskMemoryBlock::next.
Referenced by Job::ThreadWorker::garbageCollectAllocatedTasks().
Member Data Documentation
k_MaxTaskMinusOne
template<std::size_t k_MaxTask> constexpr std::size_t Job::TaskPool< k_MaxTask >::k_MaxTaskMinusOne = k_MaxTask - 1u static constexpr
Definition at line 192 of file bf_job_system.cpp.
memory
template<std::size_t k_MaxTask> TaskMemoryBlock Job::TaskPool< k_MaxTask >::memory[k_MaxTask]
Definition at line 200 of file bf_job_system.cpp.
current_block
template<std::size_t k_MaxTask> TaskMemoryBlock* Job::TaskPool< k_MaxTask >::current_block
Definition at line 201 of file bf_job_system.cpp.
The documentation for this struct was generated from the following file:
src/bf_job_system.cpp