BluFedora Job System: Job::Task Struct Reference
Job::Task Struct Reference
Public Types
using Padding = std::array< std::uint8_t, k_TaskPaddingDataSize >
Public Member Functions
Task (WorkerID worker, TaskFn fn, TaskPtr parent)
void run ()
void onFinish () noexcept
TaskPtr toTaskPtr () const noexcept
Public Attributes
TaskFn fn
The function that will be run.
AtomicInt32 num_unfinished_tasks
The number of children tasks.
AtomicInt16 ref_count
Keeps the task from being garbage collected.
std::uint8_t user_storage_size
Number of bytes available to the user in padding.
QueueType q_type
The queue type this task has been submitted to, initialized to k_InvalidQueueType.
TaskPtr parent
The parent task, can be null.
AtomicTaskPtr first_continuation
Head of linked list of tasks to be added on completion.
TaskPtr next_continuation
Next element in the linked list of continuations.
WorkerID owning_worker
The worker this task has been created on, needed for Task::toTaskPtr and various assertions.
Padding padding
User data storage.
Static Public Attributes
static constexpr std::size_t k_SizeOfMembers
static constexpr std::size_t k_TaskPaddingDataSize = k_ExpectedTaskSize - k_SizeOfMembers
Detailed Description
Definition at line 144 of file bf_job_system.cpp.
Member Typedef Documentation
Padding
using Job::Task::Padding = std::array<std::uint8_t, k_TaskPaddingDataSize>
Definition at line 159 of file bf_job_system.cpp.
Constructor & Destructor Documentation
Task()
Job::Task::Task (WorkerID worker, TaskFn fn, TaskPtr parent)
Definition at line 733 of file bf_job_system.cpp.
                                                       :
    fn{fn},
    num_unfinished_tasks{1},
    ref_count{0u},
    user_storage_size{Task::k_TaskPaddingDataSize},
    q_type{k_InvalidQueueType}, /* Set to a valid value in 'submitTask' */
    parent{parent},
    first_continuation{nullptr},
    next_continuation{nullptr},
    owning_worker{worker},
    padding{}
  {
  }
Referenced by Job::TaskPool< k_MaxTask >::allocate().
Member Function Documentation
run()
void Job::Task::run () inline
Definition at line 174 of file bf_job_system.cpp.
    {
      fn(this);
      onFinish();
    }
References fn, and onFinish().
Referenced by Job::detail::mainQueueRunTask(), and Job::ThreadWorker::run().
onFinish()
void Job::Task::onFinish () noexcept
Definition at line 754 of file bf_job_system.cpp.
  {
    // NOTE(SR):
    //   make sure to store the result in a local variable and use that for
    //   comparing against zero. otherwise, the code contains a data race
    //   because other child tasks could change `num_unfinished_tasks` in the meantime.
    const std::int32_t num_jobs_left = --num_unfinished_tasks;
    if (num_jobs_left == 0)
    {
      if (!parent.isNull())
      {
        Task* const parent_task = taskPtrToPointer(parent);
        parent_task->onFinish();
      }
      --num_unfinished_tasks;
      TaskPtr continuation = first_continuation.load();
      while (!continuation.isNull())
      {
        Task* const   task      = taskPtrToPointer(continuation);
        const TaskPtr next_task = task->next_continuation;
        taskSubmit(task, q_type);
        continuation = next_task;
      }
      --ref_count;
    }
  }
References first_continuation, Job::TaskPtr::isNull(), next_continuation, num_unfinished_tasks, onFinish(), parent, q_type, ref_count, Job::taskPtrToPointer(), and Job::taskSubmit().
Referenced by onFinish(), and run().
toTaskPtr()
TaskPtr Job::Task::toTaskPtr () const noexcept
Definition at line 747 of file bf_job_system.cpp.
  {
    const TaskHandle self_index = TaskHandle(s_JobCtx.workers()[owning_worker].task_memory.indexOf(this));
    return {owning_worker, self_index};
  }
References owning_worker.
Member Data Documentation
k_SizeOfMembers
constexpr std::size_t Job::Task::k_SizeOfMembers static constexpr
Initial value:
=
     sizeof(TaskFn) +
     sizeof(AtomicInt32) +
     sizeof(AtomicInt16) +
     sizeof(std::uint8_t) +
     sizeof(QueueType) +
     sizeof(TaskPtr) +
     sizeof(AtomicTaskPtr) +
     sizeof(TaskPtr) +
     sizeof(WorkerID)
Definition at line 146 of file bf_job_system.cpp.
k_TaskPaddingDataSize
constexpr std::size_t Job::Task::k_TaskPaddingDataSize = k_ExpectedTaskSize - k_SizeOfMembers static constexpr
Definition at line 157 of file bf_job_system.cpp.
fn
TaskFn Job::Task::fn
The function that will be run.
Definition at line 161 of file bf_job_system.cpp.
Referenced by Job::TaskPool< k_MaxTask >::allocate(), and run().
num_unfinished_tasks
AtomicInt32 Job::Task::num_unfinished_tasks
The number of children tasks.
Definition at line 162 of file bf_job_system.cpp.
Referenced by onFinish().
ref_count
AtomicInt16 Job::Task::ref_count
Keeps the task from being garbage collected.
Definition at line 163 of file bf_job_system.cpp.
Referenced by Job::ThreadWorker::garbageCollectAllocatedTasks(), onFinish(), Job::taskDecRef(), Job::taskIncRef(), and Job::taskMake().
user_storage_size
std::uint8_t Job::Task::user_storage_size
Number of bytes available to the user in padding.
Definition at line 164 of file bf_job_system.cpp.
Referenced by Job::detail::checkTaskDataSize(), and Job::detail::taskUsePadding().
q_type
QueueType Job::Task::q_type
The queue type this task has been submitted to, initialized to k_InvalidQueueType.
Definition at line 165 of file bf_job_system.cpp.
Referenced by onFinish(), and Job::taskIncRef().
parent
TaskPtr Job::Task::parent
The parent task, can be null.
Definition at line 166 of file bf_job_system.cpp.
Referenced by Job::TaskPool< k_MaxTask >::allocate(), onFinish(), and Job::taskMake().
first_continuation
AtomicTaskPtr Job::Task::first_continuation
Head of linked list of tasks to be added on completion.
Definition at line 167 of file bf_job_system.cpp.
Referenced by onFinish().
next_continuation
TaskPtr Job::Task::next_continuation
Next element in the linked list of continuations.
Definition at line 168 of file bf_job_system.cpp.
Referenced by onFinish().
owning_worker
WorkerID Job::Task::owning_worker
The worker this task has been created on, needed for Task::toTaskPtr and various assertions.
Definition at line 169 of file bf_job_system.cpp.
Referenced by Job::taskPtrToPointer(), and toTaskPtr().
padding
Padding Job::Task::padding
User data storage.
Definition at line 170 of file bf_job_system.cpp.
The documentation for this struct was generated from the following file:
src/bf_job_system.cpp