BluFedora Job System: bf::job::Task Struct Reference
bf::job::Task Struct Reference
A single 'job' to be run by this system.
Public Types
using Padding = std::array< std::uint8_t, k_TaskPaddingDataSize >
Public Member Functions
Task (WorkerID worker, TaskFn fn, TaskPtr parent)
void run ()
void onFinish () noexcept
TaskPtr toTaskPtr () const noexcept
Public Attributes
TaskFn fn
The function that will be run.
AtomicInt32 num_unfinished_tasks
The number of children tasks.
AtomicInt16 ref_count
Keeps the task from being garbage collected.
std::uint8_t user_storage_size
Number of bytes available to the user in padding.
QueueType q_type
The queue type this task has been submitted to, initalized to k_InvalidQueueType.
TaskPtr parent
The parent task, can be null.
AtomicTaskPtr first_continuation
Head of linked list of tasks to be added on completion.
TaskPtr next_continuation
Next element in the linked list of continuations.
WorkerID owning_worker
The worker this task has been created on, needed for Task::toTaskPtr and various assertions.
Padding padding
User data storage.
Static Public Attributes
static constexpr std::size_t k_SizeOfMembers
static constexpr std::size_t k_TaskPaddingDataSize = k_ExpectedTaskSize - k_SizeOfMembers
Detailed Description
A single 'job' to be run by this system.
Definition at line 141 of file bf_job_system.cpp.
Member Typedef Documentation
Padding
using bf::job::Task::Padding = std::array<std::uint8_t, k_TaskPaddingDataSize>
Definition at line 156 of file bf_job_system.cpp.
Constructor & Destructor Documentation
Task()
bf::job::Task::Task (WorkerID worker, TaskFn fn, TaskPtr parent)
Definition at line 709 of file bf_job_system.cpp.
                                                         :
      fn{fn},
      num_unfinished_tasks{1},
      ref_count{ATOMIC_VAR_INIT(0u)},
      user_storage_size{Task::k_TaskPaddingDataSize},
      q_type{k_InvalidQueueType}, /* Set to a valid value in 'bf::job::submitTask' */
      parent{parent},
      first_continuation{nullptr},
      next_continuation{nullptr},
      owning_worker{worker},
      padding{}
    {
    }
Referenced by bf::job::TaskPool< k_MaxTask >::allocate().
Member Function Documentation
run()
void bf::job::Task::run () inline
Definition at line 171 of file bf_job_system.cpp.
      {
        fn(this);
        onFinish();
      }
References fn, and onFinish().
Referenced by bf::job::detail::mainQueueRunTask(), and bf::job::ThreadWorker::run().
onFinish()
void bf::job::Task::onFinish () noexcept
Definition at line 730 of file bf_job_system.cpp.
    {
      // NOTE(SR):
      //   make sure to store the result in a local variable and use that for
      //   comparing against zero. otherwise, the code contains a data race
      //   because other child tasks could change `num_unfinished_tasks` in the meantime.
      const std::int32_t num_jobs_left = --num_unfinished_tasks;
      if (num_jobs_left == 0)
      {
        if (!parent.isNull())
        {
          Task* const parent_task = taskPtrToPointer(parent);
          parent_task->onFinish();
        }
        --num_unfinished_tasks;
        TaskPtr continuation = first_continuation.load();
        while (!continuation.isNull())
        {
          Task* const   task              = taskPtrToPointer(continuation);
          const TaskPtr next_continuation = task->next_continuation;
          taskSubmit(task, q_type);
          continuation = next_continuation;
        }
        --ref_count;
      }
    }
References first_continuation, bf::job::TaskPtr::isNull(), next_continuation, num_unfinished_tasks, onFinish(), parent, q_type, ref_count, bf::job::taskPtrToPointer(), and bf::job::taskSubmit().
Referenced by onFinish(), and run().
toTaskPtr()
TaskPtr bf::job::Task::toTaskPtr () const noexcept
Definition at line 723 of file bf_job_system.cpp.
    {
      const TaskHandle self_index = TaskHandle(s_JobCtx.workers()[owning_worker].task_memory.indexOf(this));
      return {owning_worker, self_index};
    }
References owning_worker.
Member Data Documentation
k_SizeOfMembers
constexpr std::size_t bf::job::Task::k_SizeOfMembers static constexpr
Initial value:
=
       sizeof(TaskFn) +
       sizeof(AtomicInt32) +
       sizeof(AtomicInt16) +
       sizeof(std::uint8_t) +
       sizeof(QueueType) +
       sizeof(TaskPtr) +
       sizeof(AtomicTaskPtr) +
       sizeof(TaskPtr) +
       sizeof(WorkerID)
Definition at line 143 of file bf_job_system.cpp.
k_TaskPaddingDataSize
constexpr std::size_t bf::job::Task::k_TaskPaddingDataSize = k_ExpectedTaskSize - k_SizeOfMembers static constexpr
Definition at line 154 of file bf_job_system.cpp.
fn
TaskFn bf::job::Task::fn
The function that will be run.
Definition at line 158 of file bf_job_system.cpp.
Referenced by bf::job::TaskPool< k_MaxTask >::allocate(), and run().
num_unfinished_tasks
AtomicInt32 bf::job::Task::num_unfinished_tasks
The number of children tasks.
Definition at line 159 of file bf_job_system.cpp.
Referenced by onFinish().
ref_count
AtomicInt16 bf::job::Task::ref_count
Keeps the task from being garbage collected.
Definition at line 160 of file bf_job_system.cpp.
Referenced by bf::job::ThreadWorker::garbageCollectAllocatedTasks(), onFinish(), bf::job::taskDecRef(), bf::job::taskIncRef(), and bf::job::taskMake().
user_storage_size
std::uint8_t bf::job::Task::user_storage_size
Number of bytes available to the user in padding.
Definition at line 161 of file bf_job_system.cpp.
Referenced by bf::job::detail::checkTaskDataSize(), and bf::job::detail::taskUsePadding().
q_type
QueueType bf::job::Task::q_type
The queue type this task has been submitted to, initalized to k_InvalidQueueType.
Definition at line 162 of file bf_job_system.cpp.
Referenced by onFinish(), and bf::job::taskIncRef().
parent
TaskPtr bf::job::Task::parent
The parent task, can be null.
Definition at line 163 of file bf_job_system.cpp.
Referenced by bf::job::TaskPool< k_MaxTask >::allocate(), onFinish(), and bf::job::taskMake().
first_continuation
AtomicTaskPtr bf::job::Task::first_continuation
Head of linked list of tasks to be added on completion.
Definition at line 164 of file bf_job_system.cpp.
Referenced by onFinish().
next_continuation
TaskPtr bf::job::Task::next_continuation
Next element in the linked list of continuations.
Definition at line 165 of file bf_job_system.cpp.
Referenced by onFinish().
owning_worker
WorkerID bf::job::Task::owning_worker
The worker this task has been created on, needed for Task::toTaskPtr and various assertions.
Definition at line 166 of file bf_job_system.cpp.
Referenced by bf::job::taskPtrToPointer(), and toTaskPtr().
padding
Padding bf::job::Task::padding
User data storage.
Definition at line 167 of file bf_job_system.cpp.
The documentation for this struct was generated from the following file:
src/bf_job_system.cpp