BluFedora Job System: Job::ThreadWorker Struct Reference
Job::ThreadWorker Struct Reference
Public Types
using SharedQueue = JobQueueA< k_NormalQueueSize, TaskPtr >
using WorkerQueue = JobQueueA< k_BackgroundQueueSize, TaskPtr >
using TaskAllocator = TaskPool< k_MaxTasksPerWorker >
using ThreadStorage = std::aligned_storage_t< sizeof(std::thread), alignof(std::thread)>
using TaskHandleArray = std::array< TaskHandle, k_MaxTasksPerWorker >
Public Member Functions
ThreadWorker ()=default
ThreadWorker (const ThreadWorker &rhs)=delete
ThreadWorker (ThreadWorker &&rhs)=delete
ThreadWorker & operator= (const ThreadWorker &rhs)=delete
ThreadWorker & operator= (ThreadWorker &&rhs)=delete
std::thread * worker ()
void start (const WorkerID worker_index, const std::uint64_t rng_seed)
void garbageCollectAllocatedTasks ()
bool run (const WorkerID worker_id)
void stop ()
WorkerID randomWorker () noexcept
Public Attributes
SharedQueue normal_queue = {}
WorkerQueue worker_queue = {}
TaskAllocator task_memory = {}
ThreadStorage thread = {}
TaskHandleArray allocated_tasks = {}
pcg_state_setseq_64 rng_state = {}
AtomicTaskHandleType num_allocated_tasks = 0u
Detailed Description
Definition at line 248 of file bf_job_system.cpp.
Member Typedef Documentation
SharedQueue
using Job::ThreadWorker::SharedQueue = JobQueueA<k_NormalQueueSize, TaskPtr>
Definition at line 250 of file bf_job_system.cpp.
WorkerQueue
using Job::ThreadWorker::WorkerQueue = JobQueueA<k_BackgroundQueueSize, TaskPtr>
Definition at line 251 of file bf_job_system.cpp.
TaskAllocator
using Job::ThreadWorker::TaskAllocator = TaskPool<k_MaxTasksPerWorker>
Definition at line 252 of file bf_job_system.cpp.
ThreadStorage
using Job::ThreadWorker::ThreadStorage = std::aligned_storage_t<sizeof(std::thread), alignof(std::thread)>
Definition at line 253 of file bf_job_system.cpp.
TaskHandleArray
using Job::ThreadWorker::TaskHandleArray = std::array<TaskHandle, k_MaxTasksPerWorker>
Definition at line 254 of file bf_job_system.cpp.
Constructor & Destructor Documentation
ThreadWorker() [1/3]
Job::ThreadWorker::ThreadWorker () default
ThreadWorker() [2/3]
Job::ThreadWorker::ThreadWorker (const ThreadWorker & rhs) delete
ThreadWorker() [3/3]
Job::ThreadWorker::ThreadWorker (ThreadWorker && rhs) delete
Member Function Documentation
operator=() [1/2]
ThreadWorker & Job::ThreadWorker::operator= (const ThreadWorker & rhs) delete
operator=() [2/2]
ThreadWorker & Job::ThreadWorker::operator= (ThreadWorker && rhs) delete
worker()
std::thread * Job::ThreadWorker::worker () inline
Definition at line 271 of file bf_job_system.cpp.
{ return reinterpret_cast<std::thread*>(&thread); }
Referenced by randomWorker(), start(), and stop().
start()
void Job::ThreadWorker::start (const WorkerID worker_index, const std::uint64_t rng_seed)
Definition at line 788 of file bf_job_system.cpp.
  {
    const bool is_main_thread = worker_index == k_MainThreadID;
    pcg32_srandom_r(&rng_state, std::uint64_t(worker_index) + rng_seed, std::uint64_t(worker_index) * 2u + 1u + rng_seed);
    if (is_main_thread)
    {
      initThreadWorkerID();
    }
    else
    {
      new (worker()) std::thread([]() {
          initThreadWorkerID();
          const WorkerID      thread_id = currentWorker();
          ThreadWorker* const worker    = s_JobCtx.workers() + thread_id;
#if IS_WINDOWS
          const HANDLE handle = static_cast<HANDLE>(worker->worker()->native_handle());
          // Put each thread on to dedicated core
          const DWORD_PTR affinity_mask   = 1ull << thread_id;
          const DWORD_PTR affinity_result = SetThreadAffinityMask(handle, affinity_mask);
          if (affinity_result > 0)
          {
            // Increase thread priority
            // const BOOL priority_result = SetThreadPriority(handle, THREAD_PRIORITY_HIGHEST);
            // JobAssert(priority_result != 0, "Failed to set thread priority.");
            // Name the thread
            char      thread_name[32]                    = u8"";
            wchar_t   thread_name_w[sizeof(thread_name)] = L"";
            const int c_size                             = std::snprintf(thread_name, sizeof(thread_name), "JobSystem_%i", int(thread_id));
            std::mbstowcs(thread_name_w, thread_name, c_size);
            const HRESULT hr = SetThreadDescription(handle, thread_name_w);
            JobAssert(SUCCEEDED(hr), "Failed to set thread name.");
            (void)hr;
          }
#endif
          while (!s_JobCtx.is_fully_initialized)
          {
            /* Busy Loop Wait so there is no checking of this condition in the loop itself */
          }
          while (s_JobCtx.is_running)
          {
            if (!worker->run(thread_id))
            {
              s_JobCtx.sleep();
            }
          } });
    }
  }
References Job::currentWorker(), Job::initThreadWorkerID(), JobAssert, Job::k_MainThreadID, rng_state, and worker().
Referenced by Job::initialize().
garbageCollectAllocatedTasks()
void Job::ThreadWorker::garbageCollectAllocatedTasks ()
Definition at line 850 of file bf_job_system.cpp.
  {
    if (num_allocated_tasks)
    {
      const auto allocated_tasks_bgn = allocated_tasks.begin();
#if 0
        const auto allocated_tasks_end = allocated_tasks_bgn + num_allocated_tasks;
        const auto done_end = std::partition(
         allocated_tasks_bgn,
         allocated_tasks_end,
         [this](const TaskHandle task_hdl) {
           const bool task_is_finished = finished_tasks[task_hdl];
           if (task_is_finished)
           {
             task_memory.deallocate(task_memory.fromIndex(task_hdl));
           }
           return !task_is_finished;
         });
        num_allocated_tasks = TaskHandle(std::distance(allocated_tasks_bgn, done_end));
#else
      const TaskHandleType num_tasks = num_allocated_tasks;
      TaskHandleType       read_idx  = 0u;
      TaskHandleType       write_idx = 0u;
      while (read_idx != num_tasks)
      {
        const TaskHandle task_hdl         = allocated_tasks_bgn[read_idx++];
        Task* const      task_ptr         = task_memory.fromIndex(task_hdl);
        const bool       task_is_finished = task_ptr->ref_count.load(std::memory_order_relaxed) == 0u;
        if (task_is_finished)
        {
          task_memory.deallocate(task_ptr);
        }
        else
        {
          allocated_tasks_bgn[write_idx++] = task_hdl;
        }
      }
      num_allocated_tasks = write_idx;
#endif
    }
  }
References allocated_tasks, Job::TaskPool< k_MaxTask >::deallocate(), Job::TaskPool< k_MaxTask >::fromIndex(), num_allocated_tasks, Job::Task::ref_count, and task_memory.
Referenced by Job::taskMake(), and Job::workerGC().
run()
bool Job::ThreadWorker::run (const WorkerID worker_id)
Definition at line 900 of file bf_job_system.cpp.
  {
    const bool is_main_thread = worker_id == k_MainThreadID;
    TaskPtr task_ptr = normal_queue.pop();
    if (task_ptr.isNull())
    {
      task_ptr = is_main_thread ? s_JobCtx.main_queue.pop() : worker_queue.pop();
    }
    if (task_ptr.isNull())
    {
      const WorkerID other_worker_id = randomWorker();
      if (other_worker_id != worker_id)
      {
        ThreadWorker* const other_worker = s_JobCtx.workers() + other_worker_id;
        task_ptr = other_worker->normal_queue.steal();
        if (task_ptr.isNull() && !is_main_thread)
        {
          task_ptr = other_worker->worker_queue.steal();
        }
      }
    }
    if (task_ptr.isNull())
    {
      return false;
    }
    s_JobCtx.num_available_jobs.fetch_sub(1);
    Task* const task = taskPtrToPointer(task_ptr);
    task->run();
    return true;
  }
References Job::TaskPtr::isNull(), Job::k_MainThreadID, normal_queue, Job::JobQueueA< kSize, T >::pop(), randomWorker(), Job::Task::run(), Job::JobQueueA< kSize, T >::steal(), Job::taskPtrToPointer(), and worker_queue.
Referenced by Job::detail::mainQueueRunTask(), Job::taskMake(), Job::taskSubmitQPushHelper(), and Job::waitOnTask().
stop()
void Job::ThreadWorker::stop ()
Definition at line 941 of file bf_job_system.cpp.
  {
    // Join throws an exception if the thread is not joinable. this should always be true.
    worker()->join();
    worker()->~thread();
  }
References worker().
Referenced by Job::shutdown().
randomWorker()
WorkerID Job::ThreadWorker::randomWorker () noexcept
Definition at line 948 of file bf_job_system.cpp.
  {
    const std::uint32_t num_workers = s_JobCtx.num_workers;
#if 0
      std::uint32_t weights[k_MaxThreadsSupported];
      std::uint32_t weight_sum = 0u;
      for (WorkerID i = 0u; i < num_workers; ++i)
      {
        const ThreadWorker& worker = s_JobCtx.workers()[i];
        weights[i] = worker.num_allocated_tasks;
        weight_sum += weights[i];
      }
      if (weight_sum != 0)
      {
        std::uint32_t random_number = pcg32_boundedrand_r(&rng_state, weight_sum);
        for (WorkerID i = 0u; i < num_workers; ++i)
        {
          if (random_number < weights[i])
          {
            return i;
          }
          random_number -= weights[i];
        }
      }
#endif
    return WorkerID(pcg32_boundedrand_r(&rng_state, num_workers));
  }
References Job::k_MaxThreadsSupported, rng_state, and worker().
Referenced by run().
Member Data Documentation
normal_queue
SharedQueue Job::ThreadWorker::normal_queue = {}
Definition at line 256 of file bf_job_system.cpp.
Referenced by run(), and Job::taskSubmit().
worker_queue
WorkerQueue Job::ThreadWorker::worker_queue = {}
Definition at line 257 of file bf_job_system.cpp.
Referenced by run(), and Job::taskSubmit().
task_memory
TaskAllocator Job::ThreadWorker::task_memory = {}
Definition at line 258 of file bf_job_system.cpp.
Referenced by garbageCollectAllocatedTasks(), Job::taskMake(), and Job::taskPtrToPointer().
thread
ThreadStorage Job::ThreadWorker::thread = {}
Definition at line 259 of file bf_job_system.cpp.
allocated_tasks
TaskHandleArray Job::ThreadWorker::allocated_tasks = {}
Definition at line 260 of file bf_job_system.cpp.
Referenced by garbageCollectAllocatedTasks(), and Job::taskMake().
rng_state
pcg_state_setseq_64 Job::ThreadWorker::rng_state = {}
Definition at line 261 of file bf_job_system.cpp.
Referenced by randomWorker(), and start().
num_allocated_tasks
AtomicTaskHandleType Job::ThreadWorker::num_allocated_tasks = 0u
Definition at line 262 of file bf_job_system.cpp.
Referenced by garbageCollectAllocatedTasks(), and Job::taskMake().
The documentation for this struct was generated from the following file:
src/bf_job_system.cpp