BluFedora Job System: bf::job::ThreadWorker Struct Reference
bf::job::ThreadWorker Struct Reference
Public Types
using ThreadMemory = std::aligned_storage_t< sizeof(std::thread), alignof(std::thread)>
Public Member Functions
ThreadWorker ()=default
ThreadWorker (const ThreadWorker &rhs)=delete
ThreadWorker (ThreadWorker &&rhs)=delete
ThreadWorker & operator= (const ThreadWorker &rhs)=delete
ThreadWorker & operator= (ThreadWorker &&rhs)=delete
std::thread * worker ()
void start (bool is_main_thread)
void garbageCollectAllocatedTasks (WorkerID thread_id)
bool run (WorkerID thread_id)
void stop ()
Static Public Member Functions
static void startImpl ()
static void yieldTimeSlice ()
Public Attributes
JobQueueA< k_HiPriorityQueueSize, Task * > hi_queue = {}
JobQueueA< k_NormalPriorityQueueSize, Task * > nr_queue = {}
JobQueueA< k_BackgroundPriorityQueueSize, Task * > bg_queue = {}
PoolAllocator< Task, k_MaxTasksPerWorker > task_memory = {}
std::array< TaskHandle, k_MaxTasksPerWorker > allocated_tasks = {}
ThreadMemory worker_ = {}
TaskHandleType num_allocated_tasks = 0u
bool is_running = false
bool is_fully_initialized = false
We need to wait for all workers to be initialized before we start doing work.
Detailed Description
Definition at line 169 of file bf_job_system.cpp.
Member Typedef Documentation
ThreadMemory
using bf::job::ThreadWorker::ThreadMemory = std::aligned_storage_t<sizeof(std::thread), alignof(std::thread)>
Definition at line 171 of file bf_job_system.cpp.
Constructor & Destructor Documentation
ThreadWorker() [1/3]
bf::job::ThreadWorker::ThreadWorker () default
ThreadWorker() [2/3]
bf::job::ThreadWorker::ThreadWorker (const ThreadWorker & rhs) delete
ThreadWorker() [3/3]
bf::job::ThreadWorker::ThreadWorker (ThreadWorker && rhs) delete
Member Function Documentation
operator=() [1/2]
ThreadWorker& bf::job::ThreadWorker::operator= (const ThreadWorker & rhs) delete
operator=() [2/2]
ThreadWorker& bf::job::ThreadWorker::operator= (ThreadWorker && rhs) delete
worker()
std::thread* bf::job::ThreadWorker::worker () inline
Definition at line 192 of file bf_job_system.cpp.
       {
         return reinterpret_cast<std::thread*>(&worker_);
       }
References worker_.
Referenced by start(), and stop().
start()
void bf::job::ThreadWorker::start (bool is_main_thread)
Definition at line 609 of file bf_job_system.cpp.
     {
       is_running = true;
       if (is_main_thread)
       {
         initThreadWorkerID();
       }
       else
       {
         // TODO(SR): Make this only for debug builds.
         std::memset(allocated_tasks.data(), 0xFF, sizeof(allocated_tasks));
         new (worker()) std::thread([]() {
           startImpl();
           const WorkerID      thread_id = currentWorker();
           ThreadWorker* const self      = s_JobCtx.workers + thread_id;
           while (self->is_running)
           {
             self->garbageCollectAllocatedTasks(thread_id);
             if (self->is_fully_initialized)
             {
               if (!self->run(thread_id))
               {
                 yieldTimeSlice();
                 s_JobCtx.sleep(self);
               }
             }
           }
         });
       }
     }
References allocated_tasks, bf::job::currentWorker(), garbageCollectAllocatedTasks(), bf::job::initThreadWorkerID(), is_running, startImpl(), worker(), and yieldTimeSlice().
Referenced by bf::job::initialize().
startImpl()
void bf::job::ThreadWorker::startImpl () static
Definition at line 645 of file bf_job_system.cpp.
     {
       initThreadWorkerID();
       const WorkerID      thread_id = currentWorker();
       ThreadWorker* const self      = s_JobCtx.workers + thread_id;
 #ifdef IS_WINDOWS
       const WorkerID wid    = currentWorker();
       const HANDLE   handle = static_cast<HANDLE>(self->worker()->native_handle());
       // Put each thread on to dedicated core
       const DWORD_PTR affinity_mask   = 1ull << wid;
       const DWORD_PTR affinity_result = SetThreadAffinityMask(handle, affinity_mask);
       if (affinity_result > 0)
       {
         // Increase thread priority
         const BOOL priority_result = SetThreadPriority(handle, THREAD_PRIORITY_HIGHEST);
         assert(priority_result != 0);
         // Name the thread
         if (priority_result)
         {
           char      thread_name[20]   = u8"";
           wchar_t   thread_name_w[20] = L"";
           const int c_size            = std::snprintf(thread_name, sizeof(thread_name), "bf::JobSystem_%i", int(wid));
           std::mbstowcs(thread_name_w, thread_name, c_size);
           const HRESULT hr = SetThreadDescription(handle, thread_name_w);
           (void)hr;
           assert(SUCCEEDED(hr));
         }
       }
 #endif  // _WIN32
     }
References bf::job::currentWorker(), and bf::job::initThreadWorkerID().
Referenced by start().
garbageCollectAllocatedTasks()
void bf::job::ThreadWorker::garbageCollectAllocatedTasks (WorkerID thread_id)
Definition at line 688 of file bf_job_system.cpp.
     {
       if (num_allocated_tasks)
       {
         const auto allocated_tasks_bgn = allocated_tasks.begin();
         const auto allocated_tasks_end = allocated_tasks_bgn + num_allocated_tasks;
         // NOTE(SR):
         //   Cannot use `remove_if` since it moves the removed elements,
         //   but we want swaps so that we can safely read the removed
         //   elements from done_end => allocated_tasks_end. (aka that next for_each loop)
         const auto done_end = std::partition(
          allocated_tasks_bgn,
          allocated_tasks_end,
          [thread_id](TaskHandle task_hdl) {
            Task* const task = taskPtrToPointer({thread_id, task_hdl});
            return !taskIsDone(task);
          });
         std::for_each(
          done_end,
          allocated_tasks_end,
          [&task_memory = task_memory, thread_id](TaskHandle task_hdl) {
            Task* const task = taskPtrToPointer({thread_id, task_hdl});
            task_memory.deallocateT(task);
          });
         num_allocated_tasks = TaskHandle(std::distance(allocated_tasks_bgn, done_end));
       }
     }
References allocated_tasks, num_allocated_tasks, task_memory, bf::job::taskIsDone(), and bf::job::taskPtrToPointer().
Referenced by start(), and bf::job::taskMake().
run()
bool bf::job::ThreadWorker::run (WorkerID thread_id)
Definition at line 721 of file bf_job_system.cpp.
     {
       Task* task = nullptr;
       // If is the Main Thread then prioritize grabbing from the main queue.
       if (thread_id == k_MainThreadID)
       {
         task = s_JobCtx.main_queue.pop();
       }
 #define TryGetFromQ(q_name)                                                    \
   if (!task)                                                                   \
   {                                                                            \
     task = q_name.pop();                                                       \
                                                                                \
     if (!task)                                                                 \
     {                                                                          \
       const auto other_worker_id = randomWorker();                             \
                                                                                \
       if (other_worker_id != thread_id)                                        \
       {                                                                        \
         ThreadWorker* const other_worker = s_JobCtx.workers + other_worker_id; \
                                                                                \
         task = other_worker->q_name.steal();                                   \
       }                                                                        \
     }                                                                          \
   }
       // clang-format off
       TryGetFromQ(hi_queue)
       TryGetFromQ(nr_queue)
        // The main thread should not be running tasks with background priority.
       if (thread_id != k_MainThreadID)
       {
         TryGetFromQ(bg_queue)
       }
       // clang-format on
 #undef TryGetFromQ
       if (task)
       {
         --s_JobCtx.num_queued_jobs;
         task->run();
       }
       return task != nullptr;
     }
References bg_queue, hi_queue, bf::job::k_MainThreadID, nr_queue, bf::job::Task::run(), and TryGetFromQ.
Referenced by bf::job::taskMake(), bf::job::taskSubmitQPushHelper(), and bf::job::waitOnTask().
yieldTimeSlice()
void bf::job::ThreadWorker::yieldTimeSlice () static
Definition at line 770 of file bf_job_system.cpp.
     {
       std::this_thread::yield();
       // std::this_thread::sleep_for(std::chrono::milliseconds(1));
     }
Referenced by start().
stop()
void bf::job::ThreadWorker::stop ()
Definition at line 776 of file bf_job_system.cpp.
     {
       // Joins throws an exception if the thread is not joinable. this should always be true.
       worker()->join();
       worker()->~thread();
     }
References worker().
Referenced by bf::job::shutdown().
Member Data Documentation
hi_queue
JobQueueA<k_HiPriorityQueueSize, Task*> bf::job::ThreadWorker::hi_queue = {}
Definition at line 175 of file bf_job_system.cpp.
Referenced by run(), and bf::job::taskSubmit().
nr_queue
JobQueueA<k_NormalPriorityQueueSize, Task*> bf::job::ThreadWorker::nr_queue = {}
Definition at line 176 of file bf_job_system.cpp.
Referenced by run(), and bf::job::taskSubmit().
bg_queue
JobQueueA<k_BackgroundPriorityQueueSize, Task*> bf::job::ThreadWorker::bg_queue = {}
Definition at line 177 of file bf_job_system.cpp.
Referenced by run(), and bf::job::taskSubmit().
task_memory
PoolAllocator<Task, k_MaxTasksPerWorker> bf::job::ThreadWorker::task_memory = {}
Definition at line 178 of file bf_job_system.cpp.
Referenced by garbageCollectAllocatedTasks(), bf::job::taskMake(), and bf::job::taskPtrToPointer().
allocated_tasks
std::array<TaskHandle, k_MaxTasksPerWorker> bf::job::ThreadWorker::allocated_tasks = {}
Definition at line 179 of file bf_job_system.cpp.
Referenced by garbageCollectAllocatedTasks(), start(), and bf::job::taskMake().
worker_
ThreadMemory bf::job::ThreadWorker::worker_ = {}
Definition at line 180 of file bf_job_system.cpp.
Referenced by worker().
num_allocated_tasks
TaskHandleType bf::job::ThreadWorker::num_allocated_tasks = 0u
Definition at line 181 of file bf_job_system.cpp.
Referenced by garbageCollectAllocatedTasks(), and bf::job::taskMake().
is_running
bool bf::job::ThreadWorker::is_running = false
Definition at line 182 of file bf_job_system.cpp.
Referenced by bf::job::shutdown(), bf::job::JobSystem::sleep(), and start().
is_fully_initialized
bool bf::job::ThreadWorker::is_fully_initialized = false
We need to wait for all workers to be initialized before we start doing work.
Definition at line 183 of file bf_job_system.cpp.
Referenced by bf::job::initialize().
The documentation for this struct was generated from the following file:
src/bf_job_system.cpp