BluFedora Job System: bf::job::TaskPtr Struct Reference
bf::job::TaskPtr Struct Reference
Public Member Functions
TaskPtr ()=default
TaskPtr (WorkerID worker_id, TaskHandle task_idx)
TaskPtr (std::nullptr_t)
bool isNull () const noexcept
Public Attributes
WorkerID worker_id
TaskHandle task_index
Detailed Description
Definition at line 113 of file bf_job_system.cpp.
Constructor & Destructor Documentation
TaskPtr() [1/3]
bf::job::TaskPtr::TaskPtr () default
TaskPtr() [2/3]
bf::job::TaskPtr::TaskPtr (WorkerID worker_id, TaskHandle task_idx) inline
Definition at line 120 of file bf_job_system.cpp.
                                                       :
        worker_id{worker_id},
        task_index{task_idx}
      {
      }
TaskPtr() [3/3]
bf::job::TaskPtr::TaskPtr (std::nullptr_t) inline
Definition at line 126 of file bf_job_system.cpp.
                            :
        worker_id{NullTaskHandle},
        task_index{NullTaskHandle}
      {
      }
Member Function Documentation
isNull()
bool bf::job::TaskPtr::isNull () const inline noexcept
Definition at line 132 of file bf_job_system.cpp.
{ return task_index == NullTaskHandle; }
References bf::job::NullTaskHandle, and task_index.
Referenced by bf::job::Task::onFinish(), bf::job::ThreadWorker::run(), and bf::job::tick().
Member Data Documentation
worker_id
WorkerID bf::job::TaskPtr::worker_id
Definition at line 115 of file bf_job_system.cpp.
task_index
TaskHandle bf::job::TaskPtr::task_index
Definition at line 116 of file bf_job_system.cpp.
Referenced by isNull().
The documentation for this struct was generated from the following file:
src/bf_job_system.cpp